"""`ledger.py gen-schemas [--check]` -- single generator for schemas/ (plan.md
§C4). Reads the eight row blocks + the ledgers table out of
`tables/*.json` (the closed-list single source of truth, spec.md §0.5 point
5) and produces nine files under the plugin's own `schemas/` directory:
eight `<name>.schema.json` files plus `owners.default.json`. Generation is a
pure, deterministic transform of table data -- nothing here depends on the
filesystem outside `tables/`, so re-running it reproduces the same bytes.

Generated files are never hand-edited: fix the table, regenerate.
"""
from __future__ import annotations

import json
import sys

import _lib

# (schema file stem, ledgers.json ledger name, path into tables/rows.json)
# -- the eight blocks -> eight files mapping is plan.md §C4's closed list.
_BLOCKS = [
    ("story", "story", ("story_row",)),
    ("decisions", "decisions", ("decisions_row",)),
    ("blocked", "blocked", ("blocked_row",)),
    ("feedback.suggestion", "feedback", ("feedback_rows", "suggestion")),
    ("feedback.review", "feedback", ("feedback_rows", "review")),
    ("runs.normal", "runs", ("runs_row_normal",)),
    ("runs.criterion", "runs", ("runs_row_criterion",)),
    ("launch_order", "launch_orders", ("launch_order",)),
]

_COMMENT = "generated by ledger.py gen-schemas from tables/rows.json -- DO NOT EDIT"


def _transform_field(field_schema: dict, enums: dict) -> dict:
    """One properties[field] entry (or an `items` entry): expand `$enum` in
    place, keep `$ref_to`/type/const/minimum as-is, recurse into `items`
    (which uses the same field-schema shape), drop every `_`-prefixed
    documentation key (rows.json `_doc_keys`)."""
    out = {}
    for key, value in field_schema.items():
        if key.startswith("_"):
            continue
        if key == "$enum":
            if value not in enums:
                raise _lib.RLError(
                    f"gen-schemas: unknown enum {value!r} referenced by $enum "
                    "(not a key in tables/rows.json enums)"
                )
            out["enum"] = enums[value]
        elif key == "items":
            out["items"] = _transform_field(value, enums)
        else:
            out[key] = value
    return out


def _transform_conditional(conditional: list) -> list:
    """Drop `_note` (and any other `_`-prefixed key) from each conditional
    entry; `when`/`require`/`allow_null` pass through untouched."""
    return [
        {key: value for key, value in cond.items() if not key.startswith("_")}
        for cond in conditional
    ]


def _transform_block(block: dict, enums: dict, ledger_name: str) -> dict:
    properties = {
        field: _transform_field(field_schema, enums)
        for field, field_schema in block.get("properties", {}).items()
    }
    return {
        "$comment": _COMMENT,
        "ledger": ledger_name,
        "primary_key": block["primary_key"],
        "type": "object",
        "required": block["required"],
        "additionalProperties": block["additionalProperties"],
        "properties": properties,
        "conditional": _transform_conditional(block.get("conditional", [])),
    }


def _dump(obj) -> bytes:
    return (json.dumps(obj, indent=2, sort_keys=True, ensure_ascii=False) + "\n").encode("utf-8")


def generate_schemas() -> dict:
    """Regenerate every schemas/*.schema.json + owners.default.json in
    memory. Returns {filename: content_bytes}. Pure and deterministic: same
    tables/ content in, same bytes out, no filesystem writes."""
    tables = _lib.load_tables()
    rows = tables["rows"]
    enums = rows["enums"]
    ledgers_table = tables["ledgers"]["ledgers"]  # excludes optional_ledgers

    files = {}
    for stem, ledger_name, path in _BLOCKS:
        block = rows
        for key in path:
            block = block[key]
        schema = _transform_block(block, enums, ledger_name)
        files[f"{stem}.schema.json"] = _dump(schema)

    owners = {name: entry["owner"] for name, entry in ledgers_table.items()}
    files["owners.default.json"] = _dump(owners)

    return files


def register(subparsers):
    parser = subparsers.add_parser(
        "gen-schemas",
        help="Generate schemas/*.schema.json + owners.default.json from tables/.",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Verify schemas/ matches tables/ without writing; exit 1 on any mismatch.",
    )


def run(args) -> int:
    schemas_dir = _lib.plugin_root() / "schemas"
    files = generate_schemas()

    if args.check:
        mismatched = []
        for name in sorted(files):
            path = schemas_dir / name
            if not path.exists() or path.read_bytes() != files[name]:
                mismatched.append(name)
        if mismatched:
            print(
                "gen-schemas --check: out of date with tables/: " + ", ".join(mismatched),
                file=sys.stderr,
            )
            return 1
        return 0

    schemas_dir.mkdir(parents=True, exist_ok=True)
    for name, content in files.items():
        (schemas_dir / name).write_bytes(content)
    return 0
