"""Parameter grid -> a batch of preset files. One command generates, in one shot, the N presets
needed for "changing the generation settings for the same experiment"; each one is a real file
under configs/presets/: it goes into git, is traceable, and the run_id carries the preset name
(DATA.md checklist item 9), the dirty-tree gate before launch forces a commit automatically.

Does not launch and does not occupy a card: after generation it prints the --preset usage for
each point, GPU launching still goes through gpu-run as usual.
θ sweep is a separate matter (pipeline/inject/sweep_theta.py, task names
sweep-run/sweep-curve); what this sweeps is the sampling settings
(temperature/top_p/max_tokens/seed/reasoning_effort).

Usage:
  python3 run.py preset-sweep --base gptoss_default --grid temperature=0.2,0.7,1.0
  python3 run.py preset-sweep --base gptoss_default \
      --grid temperature=0.7,1.0 --grid top_p=0.9,1.0     # cartesian product, 4 files
Generated name <base>__<key><value>[__<key><value>...]; refuses to overwrite an existing one,
--force lets it through, --dry-run only prints without writing to disk.
"""

import argparse
import copy
import itertools
import json
import sys
import time
from pathlib import Path

import preset_loader as PL

# Keys allowed into the grid: sampling settings only. api/start_date are spec switches, not
# sampling knobs; stop is a list and does not fit into a filename -- to sweep those, hand-write
# the presets instead of going through the grid.
SWEEPABLE = ("temperature", "top_p", "max_tokens", "seed", "reasoning_effort")


def parse_grid(spec):
    """"temperature=0.2,0.7" -> ("temperature", [0.2, 0.7]); values are converted to the type
    CLIENT_KEYS expects, and it errors out if the conversion fails."""
    key, sep, raw = spec.partition("=")
    if not sep or not raw:
        raise SystemExit(f"--grid must be written as key=value,value,... (now it is {spec!r})")
    if key not in SWEEPABLE:
        raise SystemExit(f"--grid only recognizes sweep keys {SWEEPABLE}, not {key!r} "
                         "(to sweep api/start_date/stop, edit the preset by hand)")
    want = PL.CLIENT_KEYS[key]
    vals = []
    for v in raw.split(","):
        v = v.strip()
        try:
            vals.append(int(v) if want is int
                        else float(v) if isinstance(want, tuple) else v)
        except ValueError:
            raise SystemExit(f"--grid {key}'s value {v!r} cannot convert to {want}")
    return key, vals


def expand(grids):
    """[(key, value list), ...] -> the list of points in the cartesian product, each point is
    {key: value}. The order is pinned: axes follow the order --grid appears in, with the later
    axis turning faster."""
    keys = [k for k, _ in grids]
    return [dict(zip(keys, combo))
            for combo in itertools.product(*(vs for _, vs in grids))]


def point_name(base, point):
    """gptoss_default + {temperature: 0.2} -> gptoss_default__temperature0.2.
    Write keys in full, do not abbreviate: the preset name is the spec description, and
    abbreviating it makes it unreadable to others."""
    return base + "".join(f"__{k}{v}" for k, v in point.items())


def make_preset(base_dict, base_name, point):
    """Overlay the grid point onto the base preset's json; rewrite desc into one traceable sentence."""
    p = copy.deepcopy(base_dict)
    p.setdefault("client", {})
    p["client"].update(point)
    kv = ",".join(f"{k}={v}" for k, v in point.items())
    p["desc"] = (f"sweep point: on top of {base_name}, {kv}; generated by run.py preset-sweep "
                 f"({time.strftime('%Y-%m-%d')}), regenerate if settings change, do not hand-edit")
    return p


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--base", required=True,
                    help="base preset name under configs/presets/")
    ap.add_argument("--grid", action="append", required=True,
                    metavar="key=value,value,...",
                    help=f"repeatable, multiple entries take the cartesian product; keys limited to {SWEEPABLE}")
    ap.add_argument("--out-dir", default=str(PL.PRESET_DIR),
                    help="directory to write to (default configs/presets/; for tests)")
    ap.add_argument("--force", action="store_true", help="overwrite an existing preset with the same name")
    ap.add_argument("--dry-run", action="store_true", help="print only, write nothing to disk")
    a = ap.parse_args(argv)

    # Run the base preset through full validation once (load_preset does this); write the original
    # json to disk, not load_preset's return value -- that one carries two runtime-only fields,
    # _name/_path
    PL.load_preset(a.base)
    base_dict = json.loads((PL.PRESET_DIR / f"{a.base}.json").read_text())

    grids = [parse_grid(s) for s in a.grid]
    dup = {k for k, _ in grids if sum(1 for kk, _ in grids if kk == k) > 1}
    if dup:
        raise SystemExit(f"the same key appears in two --grid entries: {sorted(dup)}")

    out_dir = Path(a.out_dir)
    models = PL.load_models()
    plans = []
    for point in expand(grids):
        name = point_name(a.base, point)
        preset = make_preset(base_dict, a.base, point)
        errs = PL.validate(preset, models)
        if errs:
            raise SystemExit(f"generated preset {name} failed validation:\n" + "\n".join(errs))
        path = out_dir / f"{name}.json"
        if path.exists() and not a.force:
            raise SystemExit(f"{path} already exists; change --base/--grid or use --force to overwrite "
                             "(overwriting changes settings already committed, think it through)")
        plans.append((name, path, preset))

    for name, path, preset in plans:
        if not a.dry_run:
            path.write_text(json.dumps(preset, ensure_ascii=False, indent=2)
                            + "\n")
        print(f"{'DRY ' if a.dry_run else ''}{path}  <- {preset['desc']}")
    print(f"\n{'will generate' if a.dry_run else 'generated'} {len(plans)} preset(s). "
          "next three steps:")
    print("1. git add configs/presets && commit (the dirty-tree gate for launch tasks blocks anything uncommitted)")
    print("2. run point by point: swap --preset <name> into the same task command; launch GPU jobs through gpu-run")
    print("3. put the preset name in run_id (DATA.md checklist item 9), N points means N run_ids")
    return 0


if __name__ == "__main__":
    sys.exit(main())
