"""Test infrastructure shared by every test_*.py in this suite: a wired-up
sandbox project factory, a stub task registry, and row factories that each
produce a dict valid against its ledger's schema.

Only test_lib.py exercises this module directly today; every later ticket's
test_*.py is expected to import it the same way.
"""
from __future__ import annotations

import json
import os
import subprocess
import sys
from pathlib import Path

import _lib

# The example principles table from issues/02-lib.md, reproduced verbatim --
# T07's principles-lint parser is built against exactly this column set.
METHOD_MD = """# METHOD

| principle_id | status | scope | applies_when | principle | rationale | criterion_cmd | last_tested |
|---|---|---|---|---|---|---|---|
| P001 | 【现状】 | data | always | seeds are fixed | user said so 2026-08-13 | python3 stub_registry.py check-p001 | — |
| P002 | 【想法待定】 | eval | tbd | tbd idea | discussion 2026-08-13 | | — |
"""

_SANDBOX_DIRS = ["ops", "ops/launch_orders", "plans", "reports", ".scratch"]


def make_stub_registry(root, tasks: dict) -> None:
    """Write root/stub_registry.py. `--list` prints one task name per line;
    `stub_registry.py <task> [args...]` subprocess-forwards to
    tasks[task] + the remaining args, passing through the exit code."""
    root = Path(root)
    tasks_json = json.dumps(tasks, ensure_ascii=False)
    content = f'''#!/usr/bin/env python3
"""Stub task registry -- test fixture only, not part of the plugin.
Generated by tests/helpers.make_stub_registry()."""
import json
import subprocess
import sys

TASKS = json.loads({tasks_json!r})


def main(argv):
    if not argv:
        print("usage: stub_registry.py --list | <task> [args...]", file=sys.stderr)
        return 2
    if argv[0] == "--list":
        for name in TASKS:
            print(name)
        return 0
    task = argv[0]
    if task not in TASKS:
        print(f"unknown task: {{task}}", file=sys.stderr)
        return 2
    cmd = TASKS[task] + argv[1:]
    return subprocess.run(cmd).returncode


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
'''
    (root / "stub_registry.py").write_text(content, encoding="utf-8")


def make_sandbox(tmp) -> Path:
    """Build a fully wired-up sandbox project under `tmp` and return its
    root. research-loop.json gets every ledgers key at its table default
    path, owners built from ledgers.json's owner column (or the plugin's
    generated schemas/owners.default.json if that already exists),
    registry_cmd/registry_query/record_cmd pointing at a fresh stub
    registry, runtime_factor=3, raw_data_roots=[tmp/net], and every other
    config key explicitly null."""
    root = Path(tmp)
    tables = _lib.load_tables()
    ledgers_table = tables["ledgers"]["ledgers"]
    config_keys = tables["config"]["keys"]

    make_stub_registry(root, {
        "check-p001": [
            sys.executable, "-c",
            "import json; print(json.dumps({'value': 3, 'evidence_path': 'ops/evidence.txt'}))",
        ],
        "record": [sys.executable, "-c", "pass"],
        "noop": [sys.executable, "-c", "pass"],
    })
    registry_cmd = f"{sys.executable} {root / 'stub_registry.py'}"

    owners_path = _lib.plugin_root() / "schemas" / "owners.default.json"
    if owners_path.exists():
        owners = json.loads(owners_path.read_text(encoding="utf-8"))
    else:
        owners = {name: entry["owner"] for name, entry in ledgers_table.items()}

    cfg_data = {
        "ledgers": {name: entry["default_path"] for name, entry in ledgers_table.items()},
        "owners": owners,
        "registry_cmd": registry_cmd,
        "registry_query": f"{registry_cmd} --list",
        "record_cmd": f"{registry_cmd} record",
        "runtime_factor": 3,
        "raw_data_roots": [str(root / "net")],
    }
    for key in config_keys:
        if key not in cfg_data:
            cfg_data[key] = None

    (root / "research-loop.json").write_text(
        json.dumps(cfg_data, indent=2, sort_keys=True, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )

    for sub in _SANDBOX_DIRS:
        (root / sub).mkdir(parents=True, exist_ok=True)

    (root / "METHOD.md").write_text(METHOD_MD, encoding="utf-8")

    return root


def make_git_sandbox(tmp) -> Path:
    """make_sandbox() plus `git init` with everything committed (e2e and
    dirty-tree tests need a real repo to check against)."""
    root = make_sandbox(tmp)
    subprocess.run(["git", "init", "-q"], cwd=root, check=True)
    subprocess.run(["git", "config", "user.email", "test@example.com"], cwd=root, check=True)
    subprocess.run(["git", "config", "user.name", "research-loop tests"], cwd=root, check=True)
    subprocess.run(["git", "add", "-A"], cwd=root, check=True)
    subprocess.run(["git", "commit", "-q", "-m", "init sandbox"], cwd=root, check=True)
    return root


def make_rails_sandbox(tmp) -> Path:
    """make_git_sandbox() plus everything issues/16-e2e.md's fake-rails
    scenarios need already wired and committed:

    - registry_cmd/registry_query/record_cmd repointed at scripts/fallback/
      registry.py|record.py (the real fallback trio, not make_sandbox()'s
      stub_registry.py -- fake-experiment/fake-metrics only live there);
      rails.gpu set to fallback/launch.py's command form (issues/16-e2e.md:
      "rails.gpu 指向 fallback launch.py 的命令形态" -- no code in this repo
      actually dispatches through the rails.gpu config key, callers invoke
      launch.py directly the same way test_fallback.py does, so this is
      wired for completeness/config-check rather than exercised itself).
    - an approved demo spec at .scratch/demo/spec.md containing item IT-001.
    - one demo issue ticket at .scratch/demo/issues/01-demo.md.
    - one decided decisions row D001 (affects=[]).
    - `ops/` gitignored (test_fallback.py's own convention): every file a
      scenario writes at runtime -- launch orders, jobs.json, fake-run
      artifact_dirs, runs/blocked/decisions/story jsonl -- lives under it,
      so launch.py's dirty-tree gate never trips on a scenario's own writes.
    - everything committed, so the *first* launch.py call in any scenario
      starts from a clean tree (issue's own "全部 commit（脏树门禁要过）").
    """
    root = make_git_sandbox(tmp)

    fallback_dir = _lib.plugin_root() / "scripts" / "fallback"
    registry_cmd = f"{sys.executable} {fallback_dir / 'registry.py'}"
    cfg_path = root / "research-loop.json"
    cfg_data = json.loads(cfg_path.read_text(encoding="utf-8"))
    cfg_data["registry_cmd"] = registry_cmd
    cfg_data["registry_query"] = f"{registry_cmd} --list"
    cfg_data["record_cmd"] = f"{sys.executable} {fallback_dir / 'record.py'}"
    cfg_data["rails.gpu"] = f"{sys.executable} {fallback_dir / 'launch.py'}"
    cfg_path.write_text(
        json.dumps(cfg_data, indent=2, sort_keys=True, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )

    spec_path = root / ".scratch" / "demo" / "spec.md"
    spec_path.parent.mkdir(parents=True, exist_ok=True)
    spec_header = {
        "spec_version": 1, "approved_by": None, "approved_date": None,
        "approved_digest": None, "withdrawals": [],
    }
    spec_lines = ["---\n"]
    for key, value in spec_header.items():
        spec_lines.append(f"{key}: {json.dumps(value)}\n")
    spec_lines.append("---\n")
    spec_path.write_text(
        "".join(spec_lines) + "Item IT-001 does the demo thing.\n", encoding="utf-8",
    )

    # The specs ledger's default_path (".scratch/") and the issues ledger's
    # default_path (".scratch/*/issues/") genuinely overlap on disk -- this
    # is the real, everyday layout (a feature's spec and its issue tickets
    # share one directory, e.g. this very repo's own .scratch/research-loop/
    # tree), not a corner case to fixture around. The issue body below
    # deliberately DOES repeat the spec item's id string ("IT-001"),
    # exactly as issue_min's own "spec_item(回指 item_id)" convention
    # requires every real issue ticket to; "demo/issues/01-demo.md" also
    # sorts ahead of "demo/spec.md" (path sort). A stray, non-frontmatter'd
    # scratch note in the same directory that also mentions the id is added
    # alongside it. Both used to be exactly what broke F1 (sdd/
    # final-review.md): trace_check.py's own substring-only search picked
    # whichever of these non-spec files sorted first and then failed to
    # parse it as frontmatter'd. _lib.find_spec_files requires frontmatter
    # to even count as a candidate, so both are skipped and every scenario
    # in this file resolves to the real spec.md -- this sandbox is the
    # regression coverage for that fix, not a workaround around it.
    issue_path = root / ".scratch" / "demo" / "issues" / "01-demo.md"
    issue_path.parent.mkdir(parents=True, exist_ok=True)
    issue_path.write_text(
        "# 01-demo\n\nStatus: ready-for-agent\n\n"
        "spec_item: IT-001\n\n"
        "acceptance: demo fixture ticket for the e2e self-test.\n\nBlocked by: none\n",
        encoding="utf-8",
    )
    stray_note_path = root / ".scratch" / "demo" / "notes.md"
    stray_note_path.write_text(
        "# scratch notes\n\nsomething about IT-001, no frontmatter here.\n", encoding="utf-8",
    )

    decision_row = make_decision_row(decision_id="D001", status="decided", affects=[])
    write_jsonl(root / "ops" / "decisions.jsonl", [decision_row])

    (root / ".gitignore").write_text("ops/\n", encoding="utf-8")
    subprocess.run(["git", "add", "-A"], cwd=root, check=True)
    subprocess.run(
        ["git", "commit", "-q", "-m", "wire fake rails + demo spec/issue/decision"],
        cwd=root, check=True,
    )

    approve_code = subprocess.run(
        [sys.executable, str(_lib.plugin_root() / "scripts" / "ledger.py"),
         "approve-spec", str(spec_path), "--by", "user"],
        cwd=root, capture_output=True, text=True,
    ).returncode
    if approve_code != 0:
        raise RuntimeError("make_rails_sandbox: approve-spec on the demo spec failed")

    subprocess.run(["git", "add", "-A"], cwd=root, check=True)
    subprocess.run(["git", "commit", "-q", "-m", "approve demo spec"], cwd=root, check=True)

    return root


def _run_python_script(script_path, root, args, env):
    full_env = None
    if env:
        full_env = os.environ.copy()
        full_env.update(env)
    proc = subprocess.run(
        [sys.executable, str(script_path), *args],
        cwd=str(root),
        env=full_env,
        capture_output=True,
        text=True,
    )
    return proc.returncode, proc.stdout, proc.stderr


def run_ledger(root, *args, env=None):
    """subprocess-run ledger.py with the given args, cwd=root."""
    return _run_python_script(_lib.plugin_root() / "scripts" / "ledger.py", root, args, env)


def run_script(root, script_name, *args, env=None):
    """subprocess-run scripts/<script_name> with the given args, cwd=root."""
    return _run_python_script(_lib.plugin_root() / "scripts" / script_name, root, args, env)


def write_jsonl(path, rows) -> None:
    """Write rows to path with no locking -- fixture setup only."""
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        for row in rows:
            f.write(json.dumps(row, ensure_ascii=False) + "\n")


# ---------------------------------------------------------------------------
# Row factories -- each returns a dict valid against its ledger's schema;
# keyword arguments override individual fields.
# ---------------------------------------------------------------------------


def make_blocked_row(**over):
    row = {
        "blocked_id": "B001",
        "from_layer": "deploy",
        "to_layer": "user",
        "kind": "other",
        "ref": "S001",
        "question": "what should we do here?",
        "where": None,
        "options": None,
        "evidence": ["ops/evidence.txt"],
        "raised_at": _lib.now_iso(),
        "status": "open",
        "answer": None,
        "answered_at": None,
        "answered_by": None,
        "grant_ref": None,
        "decision_ref": None,
        "schema_version": 1,
    }
    row.update(over)
    return row


def make_decision_row(**over):
    row = {
        "decision_id": "D001",
        "kind": "decision",
        "where": "spec item S1",
        "question": "which approach?",
        "options": ["A", "B"],
        "chosen": "A",
        "reason": "because of the tradeoffs discussed",
        "authorized_by": "discussed",
        "scope": None,
        "principle_ref": None,
        "affects": [],
        "blocked_ref": None,
        "decided_by": "user",
        "raised_at": _lib.now_iso(),
        "decided_at": _lib.now_iso(),
        "status": "decided",
        "superseded_by": None,
        "withdrawn_by": None,
        "withdrawn_reason": None,
        "schema_version": 1,
    }
    row.update(over)
    return row


def make_grant_row(**over):
    row = {
        "decision_id": "D001",
        "kind": "grant",
        "where": None,
        "question": "may standing authorization cover this?",
        "options": None,
        "chosen": None,
        "reason": "user granted standing authorization",
        "authorized_by": "user said so 2026-08-13",
        "scope": {"desc": "gpu jobs under 1h", "path_globs": ["ops/**"], "expires_at": None},
        "principle_ref": None,
        "affects": [],
        "blocked_ref": None,
        "decided_by": "user",
        "raised_at": _lib.now_iso(),
        "decided_at": _lib.now_iso(),
        "status": "decided",
        "superseded_by": None,
        "withdrawn_by": None,
        "withdrawn_reason": None,
        "schema_version": 1,
    }
    row.update(over)
    return row


def make_story_row(**over):
    row = {
        "claim_id": "S001",
        "claim": "method X beats the baseline",
        "evidence_runs": ["run-001"],
        "baseline_runs": ["run-000"],
        "candidate_runs": ["run-001"],
        "metric_names": None,
        "selection_rule": "best of 3 seeds",
        "derivation_command": "python3 run.py eval run-001",
        "principle_id": "P001",
        "role": "主结果",
        "decided_by": "user",
        "date": _lib.today(),
        "status": "active",
        "retired_reason": None,
        "retired_date": None,
        "retired_by": None,
        "superseded_by": None,
        "note": None,
        "schema_version": 1,
    }
    row.update(over)
    return row


def make_runs_row_normal(**over):
    row = {
        "run_id": "run-001",
        "status": "ok",
        "output_dir": "ops/runs/run-001",
        "runmeta_path": "ops/runs/run-001/RUNMETA.json",
        "metric_name": "accuracy",
        "value": 0.9,
        "n": 100,
        "filter": None,
        "seed": 0,
        "dataset_version": "v1",
        "batch_id": "S001-20260813-1",
        "arm": "实验组",
        "quick": False,
        "principle_id": None,
        "commit": None,
        "elapsed_s": 60,
        "gpu_count": 1,
        "recorded_at": _lib.now_iso(),
        "schema_version": 1,
    }
    row.update(over)
    return row


def make_runs_row_criterion(**over):
    row = {
        "run_id": "chk-P001-20260813-1",
        "status": "ok",
        "principle_id": "P001",
        "value": 3,
        "output_dir": "ops/evidence.txt",
        "runmeta_path": None,
        "metric_name": None,
        "n": None,
        "filter": None,
        "seed": None,
        "dataset_version": None,
        "batch_id": None,
        "arm": None,
        "quick": None,
        "commit": "abc1234",
        "elapsed_s": 5,
        "gpu_count": None,
        "recorded_at": _lib.now_iso(),
        "schema_version": 1,
    }
    row.update(over)
    return row


def make_launch_order(**over):
    row = {
        "run_id": "run-001",
        "spec_ref": "S1",
        "issue_ref": "01-example",
        "decision_refs": [],
        "batch_id": "S001-20260813-1",
        "promoted_from": None,
        "registry_task": "check-p001",
        "argv": ["python3", "stub_registry.py", "check-p001"],
        "env_name": "default",
        "workdir": ".",
        "expected_commit": "abc1234",
        "seed": 0,
        "dataset_version": "v1",
        "arm": "实验组",
        "filter": None,
        "quick": False,
        "resources": {"gpus": 1, "min_vram_gb": 8, "exclusive": False},
        "expected_runtime_s": 600,
        "depends_on": None,
        "expected_outputs": [],
        "metrics_cmd": "python3 stub_registry.py check-p001",
        "smoke_cmd": None,
        "retry": None,
        "artifact_dir": "ops/runs/run-001",
        "created_by": "deploy",
        "created_at": _lib.now_iso(),
        "ext": {},
    }
    row.update(over)
    return row


def make_suggestion_row(**over):
    row = {
        "fb_id": "F001",
        "kind": "suggestion",
        "date": _lib.today(),
        "layer": "deploy",
        "context": "batch S001-20260813-1",
        "problem": "the process was confusing",
        "suggestion": "clarify the docs",
        "schema_version": 1,
    }
    row.update(over)
    return row
