"""Rebuilds, character for character, the harmony prompt gpt-oss saw at the time, from
the raw appworld trajectory.

Why it's needed: the injection experiment has to cut off mid-way through a thinking
segment, splice in a tool result, and then let vLLM continue generating. The vLLM chat
endpoint can't do this -- its template only ever emits `<|start|>assistant` at the end,
and it refuses to accept history messages containing `<|channel|>` fed back in
(chat_template.jinja raises). So it has to go through the completions endpoint, and
assemble the prompt itself up to the point where "the thinking is half-written."

Since 2026-08-18 the live-run line no longer uses this file's build_prefix (the jinja
text path): /render now goes through harmony_render.render_ids, which emits token ids
directly and is identical token-for-token to the chat endpoint (the jinja text path
disagreed with the chat endpoint in two places -- "assistant turns with empty content"
and "literal <|...|> markers in the content," see the header of harmony_render.py).
build_prefix still serves the offline replay line (replay_inject / acceptance /
verify_traj); that side's convention is unchanged.

Source of the convention (changing any one of these makes the rebuilt string disagree
with what was collected):
- SYSTEM / NO_CODE_MSG / history assembly: envs/collect/run_appworld.py:19-38, 103-132
- collection parameter reasoning_effort=high: envs/runs/w0_aw_official/launch_clients.sh
- harmony template: chat_template.jinja under the model directory, applied via
  apply_chat_template
- the environment's return value was already truncated to 4000 characters at collection
  time and written into the log as-is, so the result in the log is character-for-character
  the same as what the model saw at the time (run_appworld.py:125-129)

Two self-checks (neither needs a GPU):
- check_system_verbatim(): compares the SYSTEM constant against the source file, errors
  out if it has drifted
- verify_traj(): checks the rebuilt token count against usage.in in the log (the
  server-recorded prompt_tokens), step by step

Two known sources of uncertainty (verify_traj counts and classifies them, does not
silently swallow them):
- Current date: the template calls strftime_now to get the current date, which the
  trajectory doesn't record. The w0 batch was collected on 2026-07-31, so a rebuild only
  lines up if it's run on the same day; assert_date() is responsible for blocking a
  cross-day rebuild.
- In a small number of steps, literal `<|...|>` markers got mixed into the assistant
  content (the model wrote them out itself); re-tokenizing collects them as special
  tokens, which disagrees with how the server counted them as plain text at the time.
  has_literal_harmony() is responsible for flagging these steps.
"""

import json
import re
from pathlib import Path

# [Mirrors envs/collect/run_appworld.py:19-38] check_system_verbatim() guarantees no drift
SYSTEM = """You are an autonomous agent operating a phone-like environment \
on behalf of your supervisor.

Rules:
- Each turn, write exactly ONE ```python ... ``` code block. It is executed \
in a persistent IPython shell and you ONLY see what is printed — always wrap \
calls whose result you need in print(...), e.g. \
print(apis.spotify.show_playlists(...))
- Call app APIs as: apis.{app_name}.{api_name}(...)
- Explore first: apis.api_docs.show_app_descriptions(), \
apis.api_docs.show_api_descriptions(app_name=...), \
apis.api_docs.show_api_doc(app_name=..., api_name=...)
- Your supervisor's identity: print(apis.supervisor.show_profile()) gives \
their email/phone; print(apis.supervisor.show_account_passwords()) gives \
their password for each app. NEVER guess usernames or passwords.
- Login pattern: token = apis.spotify.login(username=<supervisor email>, \
password=<password from the list>)["access_token"], then pass \
access_token=token to that app's other APIs.
- When the task is fully done, call apis.supervisor.complete_task() \
(pass answer=... if the task asks a question)."""

# [Mirrors run_appworld.py:120-122] for the step where no code block was written, this is
# the sentence sent to the model, while the log records result="NO_CODE_BLOCK" -- the two
# are different, and replay has to swap it back
NO_CODE_MSG = ("No ```python``` block found. Reply with "
               "exactly one python code block.")
NO_CODE_MARK = "NO_CODE_BLOCK"

# At collection time gpt-oss went through the chat endpoint with reasoning_effort=high
REASONING_EFFORT = "high"

# The start of the analysis channel in harmony. apply_chat_template(add_generation_prompt=True)
# only emits up to `<|start|>assistant`; the channel marker is generated by the model
# itself, so we have to append it by hand
ANALYSIS_OPEN = "<|channel|>analysis<|message|>"

# The collection date for the w0_aw_official batch (file mtimes all fall between
# 2026-07-31 06:02 and 08:14)
COLLECT_DATE = "2026-07-31"

_SRC = Path(__file__).resolve().parents[2] / "envs/collect/run_appworld.py"
_SYS_RE = re.compile(r'^SYSTEM = """(.*?)"""$', re.S | re.M)
_LITERAL_HARMONY = re.compile(r"<\|[a-z_]+\|>")
# Only these two complete strings make chat_template.jinja:263-265 raise; a lone
# <|...|> does not.
# has_literal_harmony() is far broader than this (it flags steps where the token count
# might not match).
_GUARD_STRS = ("<|channel|>analysis<|message|>", "<|channel|>final<|message|>")


def needs_guard_bypass(msgs):
    """Whether this set of messages would trip the template's <|channel|> check."""
    return any(m.get("role") == "assistant"
               and any(g in (m.get("content") or "") for g in _GUARD_STRS)
               for m in msgs)


def check_system_verbatim(src=_SRC):
    """Compares the SYSTEM constant against the source file. If the collection script changed here and this file didn't follow -> raises an error."""
    m = _SYS_RE.search(Path(src).read_text())
    if not m:
        raise RuntimeError(f"cannot find the SYSTEM literal in {src}")
    want = m.group(1).replace("\\\n", "")
    if want != SYSTEM:
        raise RuntimeError(
            f"SYSTEM does not match the collection script; the rebuilt prompt is not what the model saw at the time.\n"
            f"source file {src} length={len(want)}, this file length={len(SYSTEM)}")
    return True


def load_traj(path):
    """Reads one trajectory -> (meta, gens, envs, final). gens/envs are indexed by step."""
    recs = [json.loads(l) for l in open(path)]
    meta = recs[0]
    gens = {r["step"]: r for r in recs if r.get("type") == "gen"}
    envs = {r["step"]: r for r in recs if r.get("type") == "env"}
    final = next((r for r in recs if r.get("type") == "final"), None)
    return meta, gens, envs, final


def build_messages(meta, gens, envs, step):
    """Rebuilds the messages the model had in its request at step `step` (not including that
    step's own output).

    [Mirrors run_appworld.py:103-132]:
    - the first two entries are system + "Task from supervisor: {instruction}"
    - each round appends assistant (content only, thinking is not fed back) + user
      (execution output)
    - for a round with no code block, user is replaced with NO_CODE_MSG
    History accumulates in full; the number of turns is never truncated.
    """
    msgs = [{"role": "system", "content": SYSTEM},
            {"role": "user",
             "content": f"Task from supervisor: {meta['instruction']}"}]
    for j in sorted(k for k in gens if k < step):
        g, e = gens[j], envs.get(j)
        msgs.append({"role": "assistant", "content": g.get("content") or ""})
        if e is None:
            # The trajectory broke off at this step (collection crashed partway through);
            # rebuilding beyond this point is meaningless
            raise ValueError(f"step {j} is missing the env record, cannot rebuild step {step}")
        if e.get("action") is None or e.get("result") == NO_CODE_MARK:
            msgs.append({"role": "user", "content": NO_CODE_MSG})
        else:
            msgs.append({"role": "user",
                         "content": f"Execution output:\n{e['result']}"})
    return msgs


def build_prefix(tok, msgs, effort=REASONING_EFFORT, pin_date=COLLECT_DATE):
    """Applies the harmony template and returns the prompt string up to `<|start|>assistant`.

    pin_date: line 202 of the template calls strftime_now to write **the day it's run**
    into the prompt, so a cross-day rebuild silently produces a string different from
    what was collected. Pinning it back to the collection day makes the rebuild
    character-for-character. Pass None to turn this off (then it's assert_date's job to
    catch it).

    The placeholder part: lines 263-265 of the template raise if the assistant's content
    contains a complete `<|channel|>analysis<|message|>` or `<|channel|>final<|message|>`.
    But at collection time the vLLM server rendered it as-is -- the model really did see
    those literal markers (the model itself emitted the control markers as text). So this
    uses a placeholder to get past the check, then swaps the original text back in after
    rendering, keeping the rebuilt string character-for-character identical to what was
    collected, rather than altering the content.
    """
    subs, safe = {}, []
    for i, m in enumerate(msgs):
        c = m.get("content") or ""
        if m.get("role") == "assistant" and any(g in c for g in _GUARD_STRS):
            key = f"\x00HARMONY{i}\x00"
            subs[key] = c
            safe.append({**m, "content": key})
        else:
            safe.append(m)
    s = tok.apply_chat_template(safe, tokenize=False,
                                add_generation_prompt=True,
                                reasoning_effort=effort)
    for k, v in subs.items():
        if k not in s:
            raise RuntimeError(f"placeholder {k!r} disappeared after rendering, swapping back to the original text will fail")
        s = s.replace(k, v)
    if pin_date:
        s, n = re.subn(r"(Current date: )\d{4}-\d{2}-\d{2}",
                       lambda m: m.group(1) + pin_date, s, count=1)
        if not n:
            raise RuntimeError("the template has no Current date line, pinning the date failed")
    # The jinja template inserts an extra "\n\n" after the developer body and before <|end|>
    # (template line 248, no-tools branch); neither the chat endpoint's harmony renderer nor
    # the hand-assembled string at collection time has it (hcap has verified the two are
    # character-for-character identical). Strip only this one spot at the end of the
    # developer segment, otherwise the prompt from /render differs from the chat baseline by
    # 2 characters, and decoding diverges starting from step 0 (verified in the z1 smoke test).
    s = re.sub(r"(<\|start\|>developer<\|message\|>(?:(?!<\|end\|>).)*?)\n\n(<\|end\|>)",
               r"\1\2", s, count=1, flags=re.S)
    return s


def assert_date(prefix, expect=COLLECT_DATE):
    """The template hardcodes the current date into the prompt. A cross-day rebuild silently produces a different string; this blocks that."""
    m = re.search(r"Current date: (\d{4}-\d{2}-\d{2})", prefix)
    if not m:
        raise RuntimeError("cannot find the Current date line in the rebuilt string, the template may have changed")
    if m.group(1) != expect:
        raise RuntimeError(
            f"rebuilt date {m.group(1)} != collection date {expect}. the harmony template uses "
            f"the date of the day it runs, so a prompt rebuilt on a different day does not match collection time."
            f"either run it on the right day, or pass --assume-date explicitly to accept this discrepancy.")
    return True


def has_literal_harmony(msgs):
    """Whether literal harmony markers got mixed into messages (would make the token count not match)."""
    return any(_LITERAL_HARMONY.search(m["content"] or "") for m in msgs)


def thinking_prefix(tok, prefix, think_cut, effort=REASONING_EFFORT):
    """The full completions prompt, assembled up to the point where 'the thinking is half-written.'"""
    return prefix + ANALYSIS_OPEN + think_cut


def verify_traj(tok, path, max_steps=None):
    """Checks the rebuilt token count against usage.in in the log, returns step-by-step results.

    usage.in is the prompt_tokens recorded by the server (envs/collect/common.py:88), the
    only external yardstick that can verify "whether the rebuilt string is really what the
    model saw at the time."
    """
    meta, gens, envs, _ = load_traj(path)
    out = []
    for st in sorted(gens):
        if max_steps is not None and st >= max_steps:
            break
        want = (gens[st].get("usage") or {}).get("in")
        if want is None:
            continue
        try:
            msgs = build_messages(meta, gens, envs, st)
        except ValueError:
            break
        prefix = build_prefix(tok, msgs)
        got = len(tok.encode(prefix, add_special_tokens=False))
        out.append(dict(step=st, want=want, got=got, diff=got - want,
                        literal=has_literal_harmony(msgs)))
    return out
