"""readonly_map -- loading the read-only/non-read-only tool ground-truth table and folding labels.

The ground-truth table lives at pipeline/annotate/readonly/{appworld,bfcl}.json (finalized
2026-08-01: the criterion is "only zero-risk under speculative execution counts as read-only,"
login-type tools are judged non-read-only under the strict read-only convention; generated by
gen_tables.py, human review recorded in REVIEW.md).

The four training scripts and three eval scripts share this module in --readonly-env mode.
Only the standard library is used -- both mbert-env (transformers 4.57.6) and cprobe-env
(>=5.14) must be able to import it, so torch / transformers must never appear here.
"""
import json
from pathlib import Path

# Abstain-class sentinel: in readonly mode, every non-read-only tool folds into this one
# class. The eval side checks whether this string is present in label_map.json to tell
# whether a given run was trained in readonly mode.
NON_READONLY = "<NON_READONLY>"

READONLY_ENVS = ("appworld", "bfcl")

_TABLE_DIR = Path(__file__).resolve().parents[1] / "annotate" / "readonly"

# Hard-stop when the fraction of out-of-table labels exceeds this threshold: it's almost
# certainly a wrong --env or contaminated data. Silently folding it in would wreck the
# whole training batch into "predicts abstain for everything."
UNKNOWN_HARD_LIMIT = 0.05


def table_path(env: str) -> Path:
    return _TABLE_DIR / f"{env}.json"


def load_table(env: str) -> dict:
    """The full table: {tool: {"readonly": bool, "count": int, "reason": str, ...}}"""
    if env not in READONLY_ENVS:
        raise SystemExit(f"readonly_map: env only supports {READONLY_ENVS}, got {env!r}")
    p = table_path(env)
    if not p.exists():
        raise SystemExit(f"readonly_map: ground-truth table does not exist {p}")
    return json.loads(p.read_text())


def load_readonly_set(env: str) -> frozenset:
    """All tool names in this environment that are judged read-only."""
    return frozenset(k for k, v in load_table(env).items() if v["readonly"])


def collapse(label: str, ro_set: frozenset) -> str:
    """Read-only labels are kept as is; everything else (including out-of-table labels) folds into NON_READONLY."""
    return label if label in ro_set else NON_READONLY


def audit(labels, table: dict, where: str) -> dict:
    """Tally a batch of labels: how many read-only / non-read-only / out-of-table. Hard-stop
    immediately if the out-of-table fraction exceeds the threshold.

    labels: an iterable of tool names (one per sample, not deduplicated); where: names the
    step, for a clear error message.
    Returns a dict to write into READONLY.json / the training log.
    """
    n = n_ro = n_unknown = 0
    unknown = set()
    for lb in labels:
        n += 1
        v = table.get(lb)
        if v is None:
            n_unknown += 1
            unknown.add(lb)
        elif v["readonly"]:
            n_ro += 1
    if n == 0:
        raise SystemExit(f"readonly_map: {where} has zero samples, something upstream must be wrong")
    frac_unknown = n_unknown / n
    if frac_unknown > UNKNOWN_HARD_LIMIT:
        raise SystemExit(
            f"readonly_map: {where} has {n_unknown}/{n} ({frac_unknown:.1%}) labels not in the ground-truth table"
            f"(e.g. {sorted(unknown)[:5]}) -- exceeds the {UNKNOWN_HARD_LIMIT:.0%} threshold, "
            f"most likely --readonly-env was passed wrong or the data is mixed up, hard stop."
        )
    if n_unknown:
        print(f"[readonly_map] warning: {where} has {n_unknown}/{n} labels outside the table, "
              f"folded as non-readonly: {sorted(unknown)}")
    return dict(
        n=n, n_readonly=n_ro, n_nonreadonly=n - n_ro,
        frac_readonly=round(n_ro / n, 6),
        n_unknown=n_unknown, unknown=sorted(unknown),
    )
