#!/usr/bin/env python3
"""Pipeline driver (build design doc Sec. 7): one command, resumable, advancing at most one
step per invocation.

It is an orchestrator, not new experiment code -- every step of collect / annotate / train /
eval hands off to an existing entry point (`run.py <task>` / `run.py recipe` /
`launch_servers.py` / `launch_clients.sh` / `launch-probe` / `launch-eval`); it only does three
things itself: decide which step can advance right now, check the gates (G1-G22) on the spot,
and write the result to the state file.

Usage:
  python3 run.py pipeline --config pipeline/configs/np821_gptoss.json
  python3 run.py pipeline --config <same config> --status   # read-only print, no advance

State file: logs/pipeline/<run_family>/state.json (logs/ is in .gitignore, so state changes
do not dirty the working tree). Per-step logs sit in the same directory as <step>.log; the
subprocess's stdout/stderr all go there.

Exit codes (design doc Sec. 7):
  0  advanced one step / everything is done / the previous step's job has not finished yet
     (leave it as is and run again next time)
  3  a GPU job was launched this time (run again once it finishes)
  4  awaiting_decision: something needs a human ruling; write the decision into the batch
     config and run again
  1  gate failed (the reason lands in both the state file and stderr)

Launch registration (fix from the 2026-08-22 review C2/C7): only when t2_full / e1_tool /
e2_call actually call the launcher does the state file record a marker in `launched`. On a
second invocation for the same batch, if the criterion is not met but the marker is present,
the driver does not relaunch; it returns 0 and tells the human to check
`python3 run.py gpu-jobs` -- from now on, exit code 3 means only "this time it was really
launched"; there is no more false bookkeeping of "already launched but reporting launched
again".

Step table (appworld batch instantiation, one advance function per step; the transition table
is STEPS below):
  collect   c1_gen c2_servers c3_health c4_smoke c5_clients c6_done
  annotate  a1_stats a2_build a3_gates
  train     t1_smoke t2_full t3_close
  eval      e1_tool e2_call m1_matrix

Three implementation disciplines (design doc Sec. 7, end):
  - All probing and external actions live in `Probes`; swap in fake functions in a unit test
    and the whole state machine runs dry;
  - A criterion would rather block than pass -- the steps after t1 really run in the execution
    block; the code has TODOs marking what still needs hardening, but nowhere does "could not
    check" count as passing;
  - Every ssh probe carries `-o BatchMode=yes -o ConnectTimeout=10` (the gpu_jobs precedent;
    launch_common.has_session does not carry these two flags, do not copy it).
"""

import filecmp
import hashlib
import json
import os
import shlex
import shutil
import subprocess
import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from run import git_dirty  # noqa: E402  (precedent from launch_cmd.py:40: reuse run.py)

sys.path.insert(0, str(ROOT / "ops"))
from launch_common import local_host, probe_free  # noqa: E402

PYRUN = [sys.executable, str(ROOT / "run.py")]
LOG_ROOT = ROOT / "logs" / "pipeline"
SERVE_LOG_DIR = ROOT / "envs" / "serve_logs"   # The service launcher generated by gen_launch goes here
RUNS_DIR = ROOT / "pipeline" / "runs"

# The three artifacts gen_launch.py generates (the completion criterion is just whether they exist)
GEN_FILES = ("launch_servers.py", "launch_clients.sh", "MANIFEST.md")
# build.py's seven artifacts + param_label.py's five artifacts = the objects for the byte-for-byte rebuild comparison (design doc Sec. 9)
BUILD_FILES = ("train.jsonl", "val.jsonl", "test.jsonl", "tool_vocab.json",
               "router_stats.md", "qa_sample.txt", "ANNOTATE_REPORT.md")
PARAM_FILES = ("params/train.jsonl", "params/val.jsonl", "params/test.jsonl",
               "params/PARAM_LABEL_REPORT.md", "params/CHECK_50.md")
# check_callstr.py's output is only checked for existence: it comes from the check step, not part of the rebuild comparison
CHECK_FILE = "CALLSTR_CHECK.md"

HEALTH_MARK = "Application startup complete"   # G3's log criterion
FREE_MB = 100          # G7: tolerance for GPU memory reaching zero (a residual of tens of MiB from the driver is normal)
SSH_OPTS = ("-o", "BatchMode=yes", "-o", "ConnectTimeout=10")

# The keys in the batch config that answer "who is this run". The state file identifies
# the run by their fingerprint: if the fingerprint changes, it is a different run, and
# writes to someone else's state are refused (following the params consistency precedent
# in run.py run_recipe). weight_mode/max_bounds are deliberately excluded -- max_bounds is
# meant to be filled into the same config by a human after the a1_stats stop-point ruling.
IDENT_KEYS = ("run_family", "env", "model_short", "model_full", "data_out",
              "traj_runs", "trajs_per_unit")


# ---------------------------------------------------------------- probing and external actions

def ssh_argv(host, cmd):
    """Local runs go through bash -c, remote through ssh. BatchMode fails immediately when
    passwordless login is not set up, instead of hanging at a password prompt; ConnectTimeout
    returns within 10 seconds when the machine is unreachable."""
    if host == local_host():
        return ["bash", "-c", cmd]
    return ["ssh", "-n", *SSH_OPTS, host, cmd]


def has_session(host, sess):
    """Whether a tmux session named sess exists on host. When the probe cannot run (ssh fails),
    report it as "does not exist"; the caller decides case by case whether that counts as a gate
    failure -- c2/c5 use it to decide whether to launch, c6 uses it to distinguish "still
    running" from "all dead"; neither place will mistake an unreachable probe for completion."""
    argv = ssh_argv(host, f"tmux has-session -t {shlex.quote(sess)}")
    return subprocess.run(argv, capture_output=True, text=True).returncode == 0


def gpu_used_mb(host, gpus):
    """G7: how much GPU memory (MiB) is still held on the target card. Returns int; returns None
    when the probe cannot run -- fail-closed, and the caller treats it as "not zeroed"."""
    cmd = (f"nvidia-smi --query-gpu=memory.used --format=csv,noheader,nounits "
           f"-i {shlex.quote(str(gpus))}")
    r = subprocess.run(ssh_argv(host, cmd), capture_output=True, text=True)
    if r.returncode != 0:
        return None
    tot = 0
    for line in r.stdout.split("\n"):
        line = line.strip()
        if not line:
            continue
        try:
            tot += int(line)
        except ValueError:
            return None
    return tot


def http_get(url, timeout=10):
    """G3's second criterion. Returns (ok, body or reason). Uses curl instead of urllib:
    the runbook and MANIFEST.md both document this same curl command, so the two stay in sync."""
    r = subprocess.run(["curl", "-s", "-m", str(timeout), url],
                       capture_output=True, text=True)
    if r.returncode != 0:
        return False, f"curl rc={r.returncode} {(r.stderr or '').strip()[:120]}"
    if not r.stdout.strip():
        return False, "empty response"
    return True, r.stdout.strip()[:200]


def run_cmd(argv, cwd=None, log=None, env=None):
    """Run a subcommand. Output goes to both stdout and the per-step log; returns (rc, output text)."""
    argv = [str(a) for a in argv]
    line = shlex.join(argv)
    print("  $ " + line, flush=True)
    r = subprocess.run(argv, cwd=str(cwd or ROOT), capture_output=True,
                       text=True, env=env)
    out = (r.stdout or "") + (r.stderr or "")
    if log:
        Path(log).parent.mkdir(parents=True, exist_ok=True)
        with open(log, "a") as f:
            f.write(f"# [{time.strftime('%F %T')}] {line}\n{out}"
                    f"# rc={r.returncode}\n")
    if out.strip():
        print(out.rstrip("\n"), flush=True)
    return r.returncode, out


def boundary_counts(cfg):
    """Raw material for a1_stats: the untruncated cut count for each event. Following the
    precedent in accept_v3diff.py:21-22, push pipeline/annotate onto sys.path and import it,
    rather than duplicating the cut logic."""
    d = str(ROOT / "pipeline" / "annotate")
    if d not in sys.path:
        sys.path.insert(0, d)
    from build import collect_events            # noqa: PLC0415
    from rules import boundaries                # noqa: PLC0415
    events = collect_events([Path(r) for r in cfg["traj_runs"]], cfg["env"])
    events = [e for e in events if e["model"] == cfg["model_full"]]
    # max_bounds set to 10**9 = no truncation: the stats need "how many cuts there originally
    # were", to answer "how many did the cap of 64 cut off"
    return [len(boundaries(e["think"], max_bounds=10 ** 9)) for e in events]


def ledger_names():
    """Job names in the job ledger's active list (read-only; writes to the job ledger always go through the CLI)."""
    p = ROOT / "ops" / "jobs.json"
    if not p.exists():
        return set()
    try:
        reg = json.loads(p.read_text())
    except Exception:
        return set()
    return {j.get("name") for j in reg.get("active", [])}


def record_events():
    """Which events have been recorded for each run_id in runs.jsonl ({run_id: {"start", "finish"}})."""
    p = ROOT / "ops" / "runs.jsonl"
    out = {}
    if not p.exists():
        return out
    for line in p.read_text().split("\n"):
        line = line.strip()
        if not line:
            continue
        try:
            ev = json.loads(line)
        except Exception:
            continue
        rid = ev.get("run_id")
        if rid:
            out.setdefault(rid, set()).add(ev.get("ev"))
    return out


class Probes:
    """Injection point for probing and external actions. The default is the real functions above;
    a unit test can pass in fakes and run the whole state machine dry (design doc Sec. 7: probe
    functions are injectable, mockable)."""

    def __init__(self, **kw):
        self.git_dirty = git_dirty
        self.probe_free = probe_free
        self.has_session = has_session
        self.local_host = local_host
        self.gpu_used_mb = gpu_used_mb
        self.http_get = http_get
        self.run_cmd = run_cmd
        self.boundary_counts = boundary_counts
        self.ledger_names = ledger_names
        self.record_events = record_events
        for k, v in kw.items():
            if not hasattr(self, k):
                raise TypeError(f"Probes has no probe point {k}")
            setattr(self, k, v)


# ---------------------------------------------------------------- config reading

def load_cfg(path):
    p = Path(path)
    if not p.is_absolute():
        p = ROOT / p
    if not p.exists():
        raise SystemExit(f"batch config does not exist: {p}")
    try:
        cfg = json.loads(p.read_text())
    except Exception as e:
        raise SystemExit(f"cannot read batch config {p}: {type(e).__name__}: {e}")
    for k in ("run_family", "env", "model_short", "model_full", "data_out",
              "traj_runs", "collect"):
        if k not in cfg:
            raise SystemExit(f"batch config missing field {k}: {p}")
    for k in ("manifest", "run_id"):
        if k not in cfg["collect"]:
            raise SystemExit(f"batch config's collect section missing field {k}: {p}")
    cfg["_path"] = str(p)
    return cfg


def manifest_path(cfg):
    p = Path(cfg["collect"]["manifest"])
    return p if p.is_absolute() else ROOT / p


def manifest_of(cfg):
    """The collection manifest. Read once and cached in cfg (one invocation only advances one step, so cache invalidation is not a concern)."""
    if "_manifest" not in cfg:
        p = manifest_path(cfg)
        if not p.exists():
            raise SystemExit(f"collection manifest does not exist: {p}")
        cfg["_manifest"] = json.loads(p.read_text())
    return cfg["_manifest"]


def run_dir(cfg):
    """The collection batch directory. The manifest can override with envs_root (same rule as
    gen_launch, default envs/); when there is no manifest, build the default path -- c1 blocks
    on a missing manifest before launch, so do not blow up here first."""
    if manifest_path(cfg).exists():
        er = manifest_of(cfg).get("envs_root")
        if er:
            return Path(er) / "runs" / cfg["collect"]["run_id"]
    return ROOT / "envs" / "runs" / cfg["collect"]["run_id"]


def outdir_of(cfg):
    """The collection output directory. The name must follow the <env>_<model_key> standard name
    (G5); gen_launch enforces the rename, and this builds the name with the same rule on the
    spot, rather than copying it from the manifest."""
    return run_dir(cfg) / f"{cfg['env']}_{cfg['model_short']}"


def smoke_dir(cfg):
    return run_dir(cfg) / "smoke" / f"{cfg['env']}_{cfg['model_short']}"


def k_of(cfg):
    return int(cfg.get("trajs_per_unit", 1))


def seeds_of(cfg):
    return list(cfg["collect"].get("seeds") or [])


def data_out(cfg):
    return Path(cfg["data_out"])


def data_root(cfg):
    """--data-root for launch-probe / launch-eval: the dataset version directory (one subdirectory
    per model under it), i.e. the parent of data_out."""
    return data_out(cfg).parent


def unit_list(path):
    """The official task list: one task_id per line, the file has no trailing newline (the G9
    pitfall); split by line and drop empty lines. Same rule as build.read_unit_list."""
    return [ln.strip() for ln in Path(path).read_text().split("\n") if ln.strip()]


def split_lists(cfg):
    files = cfg.get("official_split_files") or {}
    return {k: unit_list(v) for k, v in files.items()}


def n_units(cfg):
    return sum(len(v) for v in split_lists(cfg).values())


def train_cfg(cfg):
    return cfg.get("train") or {}


def batches_of(cfg):
    return list((train_cfg(cfg).get("batches") or {}).keys())


def cells_of(cfg):
    return list(train_cfg(cfg).get("cells") or [])


def run_ids_of(cfg):
    """The run_id for train/eval, the name that stays consistent across the four places: <batch>_<model>_<cell>."""
    return [f"{b}_{cfg['model_short']}_{c}"
            for b in batches_of(cfg) for c in cells_of(cfg)]


def placement_of(cfg, batch, stage=""):
    """Path to the card-scheduling table. train.placement in the config gives a base name (e.g.
    ops/np821_placement.json); the real table is one per batch -- following p1's naming scheme
    (ops/p1b06_placement.json, ops/p1b06_eval_tool_placement.json), look it up in the same
    directory by batch name. If not found, block; do not guess. stage is
    "" / "eval_tool" / "eval_call"."""
    base = Path(train_cfg(cfg).get("placement") or "ops/placement.json")
    if not base.is_absolute():
        base = ROOT / base
    tail = f"_{stage}_placement.json" if stage else "_placement.json"
    return base.parent / f"{batch}{tail}"


# ---------------------------------------------------------------- small utilities

def file_contains(path, needle, block=1 << 20):
    """Find a line in a large log. Read it streamed in chunks; do not load a several-hundred-MB vLLM log entirely into memory."""
    p = Path(path)
    if not p.exists():
        return False
    nb = needle.encode()
    tail = b""
    with open(p, "rb") as f:
        while True:
            buf = f.read(block)
            if not buf:
                return False
            if nb in tail + buf:
                return True
            # Keep len(needle)-1 bytes to join with the next chunk, so a line crossing a chunk boundary is not missed
            tail = buf[-(len(nb) - 1):] if len(nb) > 1 else b""


def traj_files(d, env):
    return sorted(Path(d).glob(f"{env}_*.jsonl")) if Path(d).is_dir() else []


def _first_last(path, tail_bytes=65536):
    """The trajectory file's first line (meta) and last line (final). Reads only the first line
    plus the last 64KB -- G6 needs to glance at each of 1260 files on NFS, and reading the whole
    file in is too expensive; in the final record, eval is already truncated to 600 characters,
    so one record is nowhere near 64KB."""
    p = Path(path)
    if not p.is_file():
        return None, None
    with open(p, "rb") as f:
        first = f.readline()
        f.seek(0, 2)
        size = f.tell()
        f.seek(max(0, size - tail_bytes))
        tail = f.read()
    lines = [ln for ln in tail.decode("utf-8", "replace").split("\n") if ln.strip()]
    if not lines:
        return None, None
    return first.decode("utf-8", "replace").strip() or None, lines[-1]


def is_final(path):
    """Whether the last line is type=final (the per-file criterion for G4/G6)."""
    _, last = _first_last(path)
    if last is None:
        return False
    try:
        return json.loads(last).get("type") == "final"
    except Exception:
        return False


def meta_seed(path):
    """The seed this trajectory used, from the trajectory's meta (gen_settings.seed); returns None if it cannot be read."""
    first, _ = _first_last(path)
    if first is None:
        return None
    try:
        return (json.loads(first).get("gen_settings") or {}).get("seed")
    except Exception:
        return None


def final_steps(path):
    """The steps field in the last line's final record (needed for counting tasks that hit the 30-step cap); returns None if it cannot be read."""
    _, last = _first_last(path)
    if last is None:
        return None
    try:
        rec = json.loads(last)
        return rec.get("steps") if rec.get("type") == "final" else None
    except Exception:
        return None


def pct(sorted_vals, q):
    """Index-based percentile: take the element at index floor(q*n) (0-indexed), no interpolation, for easy reconciliation.

    The definition must match q() in the pipeline/annotate/build.py:468 report verbatim -- the
    p50/p90/p99 that a1_stats prints into the state file are what a human uses to decide
    max_bounds, and after a2, build.py writes the same-named numbers into the ANNOTATE_REPORT
    archive; the two definitions disagree by one slot exactly when q*n is an integer
    (2026-08-22 review C4). This follows build's index-based version, so one batch of data has
    only one definition.
    """
    n = len(sorted_vals)
    return sorted_vals[min(n - 1, max(0, int(q * n)))]


def dist_of(counts):
    s = sorted(counts)
    return dict(n_events=len(s), min=s[0], p50=pct(s, 0.5), p90=pct(s, 0.9),
                p99=pct(s, 0.99), max=s[-1],
                over_32=sum(1 for x in s if x > 32),
                over_64=sum(1 for x in s if x > 64),
                over_128=sum(1 for x in s if x > 128),
                over_256=sum(1 for x in s if x > 256))


def client_sessions(cfg):
    """The tmux session name launch_clients.sh will start. The naming scheme follows gen_launch.py's
    `tm "{prefix}_$1_s$7"`; prefix defaults to the first two segments of run_id joined together."""
    mf = manifest_of(cfg)
    prefix = mf.get("client_session_prefix")
    if not prefix:
        parts = mf["run_id"].split("_")
        tail = "".join(parts[:2]) if len(parts) >= 2 else mf["run_id"]
        prefix = f"new1_{tail}"
    out = []
    for c in mf["clients"]:
        for sid in range(c["num_shards"]):
            out.append(f"{prefix}_{c['tag']}_s{sid}")
    return out


def client_log(cfg, sess):
    return run_dir(cfg) / "logs" / f"{sess}.log"


def srv_job_name(cfg, i):
    """The job name for a service piece in the job ledger. Following the p1 precedent, one entry per instance (p1_srv_a/p1_srv_b)."""
    return f"{cfg['collect']['run_id']}_srv_{chr(ord('a') + i)}"


def step_log(cfg, name):
    return LOG_ROOT / cfg["run_family"] / f"{name}.log"


def head_lines(lines, n=8):
    body = "\n".join("  " + x for x in lines[:n])
    return body + (f"\n  ...{len(lines)} lines total" if len(lines) > n else "")


# ---------------------------------------------------------------- events and state

def _ev(status, event, detail="", decision=None, advance=False):
    return dict(status=status, event=event, detail=detail,
                decision_needed=decision, advance=advance)


def advanced(event, detail=""):
    """This step is done; move the pointer forward one slot."""
    return _ev("ready", event, detail, advance=True), 0


def launched(event, detail="", advance=True):
    """A GPU job was launched this time; run again once it finishes."""
    return _ev("launched", event, detail, advance=advance), 3


def blocked(event, detail):
    """The gate did not pass. The reason lands in the state file and stderr; the pointer does not move."""
    return _ev("blocked", event, detail), 1


def waiting(event, detail):
    """The job launched by the previous step is still running -- neither failed nor done: leave it as is and wait for the next run."""
    return _ev("ready", event, detail), 0


def decide(event, detail, question):
    """Stop point: something needs a human ruling; write the decision into the batch config and run again."""
    return _ev("awaiting_decision", event, detail, decision=question), 4


def ident_of(cfg):
    ident = {k: cfg.get(k) for k in IDENT_KEYS}
    ident["collect_run_id"] = cfg["collect"]["run_id"]
    blob = json.dumps(ident, sort_keys=True, ensure_ascii=False)
    return hashlib.sha1(blob.encode()).hexdigest()[:12]


def fresh_state(cfg):
    return dict(config=cfg["_path"], run_family=cfg["run_family"],
                ident=ident_of(cfg), stage=STEPS[0]["stage"],
                step=STEPS[0]["name"], status="ready", reason=None,
                decision_needed=None, launched={}, history=[])


def state_path(cfg):
    return LOG_ROOT / cfg["run_family"] / "state.json"


def load_state(cfg):
    """Read the state. If it cannot be read / keys are missing / the step name is unrecognized /
    the batch identity does not match, refuse to write on top of it in every case -- following
    the params consistency precedent in run.py run_recipe: better to have a human take a look
    than to let it overwrite another run's state."""
    p = state_path(cfg)
    if not p.exists():
        return fresh_state(cfg)
    try:
        st = json.loads(p.read_text())
    except Exception as e:
        raise SystemExit(f"cannot read state file {p}: {type(e).__name__}: {e};"
                         "manually confirm its origin, delete it, then re-run (the driver won't overwrite state it can't understand)")
    if not isinstance(st, dict):
        raise SystemExit(f"state file is not an object: {p}; manually confirm, then delete it and re-run")
    miss = [k for k in ("run_family", "ident", "step", "status") if k not in st]
    if miss:
        raise SystemExit(f"state file missing field {miss}: {p}; manually confirm, then delete it and re-run")
    if st["step"] != "done" and st["step"] not in STEP_NAMES:
        raise SystemExit(f"unrecognized step name in the state file: {st['step']}({p});"
                         "manually confirm, then delete it and re-run")
    if st["ident"] != ident_of(cfg) or st["run_family"] != cfg["run_family"]:
        raise SystemExit(
            f"{p} records a run for a different set of batch parameters (ident={st['ident']},"
            f"this run's ident={ident_of(cfg)}), refusing to overwrite;"
            f"use a different run_family, or align the config back to the original set")
    st.setdefault("history", [])
    st.setdefault("reason", None)
    st.setdefault("decision_needed", None)
    # The launch marker travels with the state file (old state without this key -> fill in an empty one, treat old bookkeeping as not launched)
    if not isinstance(st.get("launched"), dict):
        st["launched"] = {}
    st["config"] = cfg["_path"]
    return st


def save_state(cfg, st):
    """Atomic write: tmp + os.replace, following run.py save_state."""
    d = state_path(cfg).parent
    d.mkdir(parents=True, exist_ok=True)
    tmp = d / "state.json.tmp"
    tmp.write_text(json.dumps(st, ensure_ascii=False, indent=1))
    os.replace(tmp, d / "state.json")


def apply_event(st, step, event):
    """Write the result of one advance into the state: state fields + one history entry. Only
    advance moves the pointer; moving it to the end means done."""
    st["status"] = event["status"]
    st["reason"] = event["detail"] or None
    st["decision_needed"] = event["decision_needed"]
    st["history"].append(dict(t=time.strftime("%F %T"), step=step["name"],
                              event=event["event"], detail=event["detail"]))
    if event["advance"]:
        i = STEP_NAMES.index(step["name"])
        if i + 1 < len(STEPS):
            st["step"] = STEPS[i + 1]["name"]
            st["stage"] = STEPS[i + 1]["stage"]
        else:
            st["step"] = "done"
            st["status"] = "done"
    return st


# --------------------------------------------------- launch marker (fix from review C2/C7)

def launch_key(step_name, batch):
    """The key for the launch marker. One entry per step per batch; different batches / different steps never cross."""
    return f"{step_name}:{batch}"


def launch_marker(state, key):
    d = state.get("launched")
    return d.get(key) if isinstance(d, dict) else None


def mark_launched(state, key, what=""):
    """Only recorded once the driver actually calls the launcher (after rc=0)."""
    if not isinstance(state.get("launched"), dict):
        state["launched"] = {}
    state["launched"][key] = {"t": time.strftime("%F %T"), "what": what}
    return state["launched"][key]


def already_launched(what, key, mark, extra=""):
    """The criterion is not met but this batch's marker is present: do not relaunch, wait as is (return 0).

    Never report launched/return 3 here -- for a session already running, the launcher just
    prints SKIP and still returns 0, so treating rc as "launched this time" would write a false
    launch record; and for a slot that has already finished, its session is long gone, so a
    blind launch would append it a false RUNMETA and stuff run_id back into the job ledger's
    active list (review C2/C7).
    """
    return waiting(f"{what} was already launched earlier, not relaunching this time",
                   f"mark {key} records launch time {mark.get('t')}"
                   + (f"({mark.get('what')})" if mark.get("what") else "")
                   + "; the criteria are not yet met, it may still be running or may have died partway. Check where it stands:\n"
                     "  python3 run.py gpu-jobs\n"
                     "  python3 run.py gpu-jobs watch\n"
                   + (extra + "\n" if extra else "")
                   + f"after confirming that batch is neither running nor finished (e.g. it crashed), delete "
                     f"{key!r} under launched in the state file and re-run, only then will the driver relaunch")


# ---------------------------------------------------------------- small gate pieces

def gate_clean_tree(pr, what):
    """G1: the working tree must be clean before launch. Returns None to mean pass, otherwise
    returns a blocked event. The HEAD stored in the record only leads back to the real code
    when the working tree is clean (the CLAUDE.md hard rule), so there is no --allow-dirty
    bypass here: the driver is an orchestrator, and committing is a human's job."""
    lines = pr.git_dirty()
    if lines is None:
        return blocked("G1 cannot probe the worktree",
                       f"git status failed, treating as a dirty tree, refusing {what};"
                       "confirm the git environment, commit first, then re-run")
    if lines:
        return blocked("G1 worktree is dirty",
                       f"{len(lines)} lines uncommitted, refusing {what} -- "
                       f"commit before launching (CLAUDE.md hard rule):\n{head_lines(lines)}")
    return None


def manifest_sha1(cfg):
    """The sha1 of the collection manifest file's bytes. Returns None if the file does not exist."""
    p = manifest_path(cfg)
    if not p.is_file():
        return None
    return hashlib.sha1(p.read_bytes()).hexdigest()


def gate_manifest_unchanged(cfg, state, what):
    """C9: which manifest an artifact was generated from must match.

    When c1_gen generates (or claims) the three launch artifacts, it records that manifest's
    sha1 into the state at that time; c2/c5, which actually execute those three things,
    recompute and compare it again. If a human changes the card number or session name in the
    manifest but forgets to regenerate with `gen-launch --force`, this blocks on the spot --
    otherwise c2 would pass G2 with the new card number but run launch_servers.py that still
    has the old card number written in it, bring vLLM up on the old card and old session, and
    then c3 would wait forever for a log that will never appear.

    Returns None to mean pass; for old state that never recorded a sha1, fill one in and then
    pass (a missing record does not count as a failure).
    """
    cur = manifest_sha1(cfg)
    if cur is None:
        return blocked("collection manifest does not exist", str(manifest_path(cfg)))
    old = state.get("manifest_sha1")
    if not old:
        state["manifest_sha1"] = cur
        return None
    if old != cur:
        return blocked(
            "manifest does not match the one used when generating the launch artifacts",
            f"{manifest_path(cfg)} was modified after c1_gen generated the three launch artifacts"
            f"(recorded sha1 {old[:12]}, now {cur[:12]}); under {run_dir(cfg)}"
            f"the card number, session name, and port in launch_servers.py / launch_clients.sh"
            f"are still the old ones, running {what} directly would target the wrong card. Regenerate first:\n"
            f"  python3 run.py gen-launch --config {manifest_path(cfg)} --force\n"
            "before regenerating, also double-check whether servers[].gpu is really free, and whether the session name"
            "was updated accordingly; after generating, delete manifest_sha1 in the state file logs/pipeline/"
            f"{cfg['run_family']}/state.json (or set it to the new value)"
            "then re-run, only then will the driver recognize this new one")
    return None


def smoke_traj_check(d, k, seeds, env):
    """G4's criterion: K files, each with a final last line, each meta's seed matching the seed
    table position by position. Returns (ok, text explaining which one failed)."""
    if seeds and len(seeds) < k:
        # If the seed table is shorter than K: report the criterion as failed directly, do not let
        # seeds[i] raise IndexError and turn a ready-made blocked into a traceback (review C10)
        return False, (f"the seed table has only {len(seeds)} entries ({seeds}), at {k} per task"
                       f"it needs {k}, cannot align position by position")
    files = traj_files(d, env)
    if len(files) != k:
        return False, (f"{d} has {len(files)} trajectory files, at {k} per task it should be "
                       f"{k}: {[f.name for f in files]}")
    probs = []
    for i in range(k):
        if k > 1:
            hit = [f for f in files if f.stem.endswith(f"_r{i}")]
            if len(hit) != 1:
                probs.append(f"trajectory {i} (filename ending in _r{i}) found {len(hit)}")
                continue
            f = hit[0]
        else:
            f = files[0]
        if not is_final(f):
            probs.append(f"{f.name} last line is not type=final")
        if seeds:
            got = meta_seed(f)
            if got != seeds[i]:
                probs.append(f"{f.name}'s gen_settings.seed={got},"
                             f"seed table position {i} is {seeds[i]}")
    return (not probs), "\n".join(probs)


def annotate_artifacts(cfg):
    """The outputs the annotate stage should have. The first 12 are produced by build +
    param_label (the objects for the byte-for-byte rebuild comparison); the 13th,
    CALLSTR_CHECK.md, comes from the gate script and is only checked for existence."""
    return list(BUILD_FILES) + list(PARAM_FILES) + [CHECK_FILE]


def missing_artifacts(cfg):
    out = data_out(cfg)
    return [n for n in annotate_artifacts(cfg) if not (out / n).is_file()]


def train_log_records(run_out):
    p = Path(run_out) / "train_log.jsonl"
    if not p.is_file():
        return []
    recs = []
    for line in p.read_text().split("\n"):
        line = line.strip()
        if not line:
            continue
        try:
            recs.append(json.loads(line))
        except Exception:
            continue
    return recs


def smoke_train_check(run_out, cell):
    """The machine-checkable half of G14: smoke really finished + ctool's ALIGN_CHECK PASS.

    Criterion = train_log.jsonl has event=start and event=done, and best/ exists; ctool also
    requires ALIGN_CHECK.json's PASS. Missing done or missing best/ always fails -- "finished
    running" is not something to leave ambiguous.

    "loss is decreasing" is only judged when there are two or more event=step records: the
    three training scripts write a step record only every 50 optimization steps
    (train_causal_tool.py:422's `if gstep % 50 == 0`), while --smoke pins the training amount
    at 6-16 optimization steps, so a smoke run that completes usually has zero step records
    (observed in logs/new1_p1b17_gptoss_ctool_smoke_gc_t108g0.log: [[EXITCODE:0]] +
    event=done, 0 event=step records). When there are fewer than two records, this does not
    block; it just records "loss sequence too short, not judged" into this step's history
    detail (review C6).

    Returns (ok, reason for failure, a note worth recording even when it passes).

    TODO (execution-block hardening): "decreasing" currently only compares the first and last
    loss records; whether a real run should look at slope, and whether to also verify the
    checkpoint can be loaded back (G15), will be decided once the first batch's actual
    train_log comes in.
    """
    p = Path(run_out)
    if not (p / "train_log.jsonl").is_file():
        return False, f"{p}/train_log.jsonl does not exist (smoke has not run, or this is not the right output dir)", ""
    recs = train_log_records(p)
    if not any(r.get("event") == "start" for r in recs):
        return False, f"{p}/train_log.jsonl has no event=start record", ""
    if not any(r.get("event") == "done" for r in recs):
        n_eval = sum(1 for r in recs if r.get("event") == "eval")
        return False, (f"{p}/train_log.jsonl has no event=done"
                       f"(smoke has not finished; {n_eval} eval records so far)"), ""
    if not (p / "best").is_dir():
        return False, f"{p}/best does not exist (smoke finished but did not save the best checkpoint)", ""
    note = ""
    losses = [r["loss"] for r in recs
              if r.get("event") == "step" and isinstance(r.get("loss"), (int, float))]
    if len(losses) >= 2:
        if losses[-1] >= losses[0]:
            return False, f"{p}'s loss did not drop: first {losses[0]} last {losses[-1]}", ""
    else:
        note = (f"{p}: train_log.jsonl has only {len(losses)} event=step records,"
                "the loss sequence is too short to judge whether this cell's loss dropped (smoke writes one every 50 optimizer steps,"
                "it doesn't run that many)")
    if cell == "ctool":
        a = p / "ALIGN_CHECK.json"
        if not a.is_file():
            return False, f"{p}/ALIGN_CHECK.json does not exist (G13 alignment check has not run)", ""
        try:
            rep = json.loads(a.read_text())
        except Exception as e:
            return False, f"cannot read {a}: {type(e).__name__}: {e}", ""
        if not rep.get("PASS"):
            return False, (f"{a}'s PASS={rep.get('PASS')}"
                           f"(hidden maxdiff {rep.get('maxdiff_hidden')})"), ""
    return True, "", note


def full_train_check(run_out):
    """t2's completion criterion: best/ exists + train_log reaches event=done.
    TODO (execution-block hardening): "3 epochs completed" currently just trusts the done
    record the training script writes itself; a real epoch-by-epoch check needs the eval
    record count convention pinned down first, to be settled once the first full run finishes."""
    p = Path(run_out)
    if not (p / "best").is_dir():
        return False, f"{p}/best does not exist"
    recs = train_log_records(p)
    if not any(r.get("event") == "done" for r in recs):
        n_eval = sum(1 for r in recs if r.get("event") == "eval")
        return False, f"{p}/train_log.jsonl has no event=done ({n_eval} epochs finished so far)"
    return True, ""


def theta_all_null(ctool_run):
    """If neither risk tier has a resolution -> record this batch's call tier as N/A (the
    convention in gates.md Sec. 3.4). If the report cannot be read, treat it as "not N/A" --
    do not let a file read failure pass itself off as a legitimately missing cell."""
    p = Path(ctool_run) / "REPLAY_REPORT.json"
    if not p.is_file():
        return False
    try:
        rep = json.loads(p.read_text())
    except Exception:
        return False
    ch = rep.get("chosen_theta")
    if not isinstance(ch, dict) or not ch:
        return False
    return all(v is None for v in ch.values())


# ---------------------------------------------------------------- collect: six steps

def step_c1_gen(cfg, state, pr=None):
    """c1_gen: generate the three launch artifacts for the collection batch from the manifest.
    If they already exist, treat it as done -- gen-launch without --force refuses to
    overwrite, so do not force it to run."""
    pr = pr or Probes()
    d = run_dir(cfg)
    have = [n for n in GEN_FILES if (d / n).exists()]
    if len(have) == len(GEN_FILES):
        # Claiming an existing artifact also records its sha1: c2/c5 use it to check "was the
        # artifact generated from the current manifest" (C9). A claimed one can only be recorded on
        # the basis of "the human vouches it matches" -- but once it is recorded, a later manifest
        # change gets caught.
        h = manifest_sha1(cfg)
        if h:
            state["manifest_sha1"] = h
        return advanced("the three generated artifacts already exist", str(d))
    if have:
        miss = [n for n in GEN_FILES if n not in have]
        return blocked("only half the set of generated artifacts exist",
                       f"{d} already has {have}, missing {miss}; gen-launch without --force will"
                       "refuse to overwrite -- manually confirm the origin of the leftover files, delete them, or add --force yourself to regenerate")
    mp = manifest_path(cfg)
    if not mp.exists():
        return blocked("collection manifest does not exist", str(mp))
    rc, _ = pr.run_cmd(PYRUN + ["gen-launch", "--config", str(mp)],
                       cwd=ROOT, log=step_log(cfg, "c1_gen"))
    if rc != 0:
        return blocked("gen-launch exited non-zero",
                       f"rc={rc}; log {step_log(cfg, 'c1_gen')}")
    miss = [n for n in GEN_FILES if not (d / n).exists()]
    if miss:
        return blocked("gen-launch finished but the generated artifacts are incomplete", f"{d} is missing {miss}")
    h = manifest_sha1(cfg)
    if h:
        state["manifest_sha1"] = h
    return advanced("the three generated artifacts have been generated", str(d))


def step_c2_servers(cfg, state, pr=None):
    """c2_servers: G1 dirty-tree check -> G2 live probe for a free card -> launch vLLM (launch_servers.py is idempotent)."""
    pr = pr or Probes()
    bad = gate_manifest_unchanged(cfg, state, "launch collection service")
    if bad:
        return bad
    mf = manifest_of(cfg)
    servers = mf["servers"]
    bad = gate_clean_tree(pr, "launch collection service")
    if bad:
        return bad
    # Session existence must be checked before probing the card: once the service is up it holds
    # the card itself, so probing again will never show FREE; getting the order backwards would
    # leave an already-launched batch permanently stuck on blocked
    down = [s for s in servers if not pr.has_session(s["host"], s["session"])]
    if not down:
        return advanced(f"all {len(servers)} service sessions are up",
                        ", ".join(s["session"] for s in servers))
    busy = []
    for s in down:
        ok, why = pr.probe_free(s["host"], str(s["gpu"]))
        if not ok:
            busy.append(f"{s['host']}:{s['gpu']} {why}")
    if busy:
        return blocked("G2 target card is not FREE",
                       "\n".join(busy) + "\nto change cards, edit servers[].gpu in the manifest "
                       "and the session name, then re-run gen-launch with --force")
    rc, _ = pr.run_cmd([sys.executable, "launch_servers.py"],
                       cwd=run_dir(cfg), log=step_log(cfg, "c2_servers"))
    if rc != 0:
        return blocked("launch_servers.py exited non-zero",
                       f"rc={rc}; log {step_log(cfg, 'c2_servers')}")
    return launched(f"{len(down)} vLLM instances launched",
                    "bringing them all up takes a few minutes, next step c3_health verifies G3")


def step_c3_health(cfg, state, pr=None):
    """c3_health: G3 requires each instance's log to show startup complete and /v1/models to respond.

    When the log does not have that line yet, probe the tmux session once more: session still
    there = the service is warming up, leave the state as is and wait for the next run; session
    not found = this instance came up and then died (vLLM running out of GPU memory and
    crashing on the spot is the most common case), and that log line will never appear, so
    waiting longer is pointless -- block, and lay out the session name and log path for a human
    to read (review C8). has_session also returns False when the ssh probe cannot run, so the
    wording says "could not probe" rather than asserting "crashed".
    """
    pr = pr or Probes()
    bad, dead = [], []
    for s in manifest_of(cfg)["servers"]:
        log = SERVE_LOG_DIR / f"{s['session']}.log"
        if not file_contains(log, HEALTH_MARK):
            if pr.has_session(s["host"], s["session"]):
                bad.append(f"{s['session']}: log does not yet have {HEALTH_MARK!r}"
                           f"(session is still up, treat as warming up and wait); log {log}")
            else:
                dead.append(f"{s['session']}({s['host']}:{s['port']}): "
                            f"tmux session cannot be found, and the log has no {HEALTH_MARK!r};"
                            f"log {log}")
            continue
        ok, why = pr.http_get(f"http://{s['host']}:{s['port']}/v1/models")
        if not ok:
            bad.append(f"{s['host']}:{s['port']}/v1/models did not respond: {why}")
    if dead:
        return blocked("G3 some instance's session cannot be found",
                       "\n".join(dead + bad)
                       + "\nthese instances will not come back on their own: read the tail of the log to find the cause"
                         "(out of GPU memory and port already in use are the most common), after fixing it, under "
                       + str(run_dir(cfg)) + " re-run "
                         "`python3 launch_servers.py` (idempotent, only fills in the ones that did not come up)")
    if bad:
        return waiting("G3 services not all up", "\n".join(bad))
    n = len(manifest_of(cfg)["servers"])
    return advanced(f"G3 {n} instances all green", "log shows startup complete and /v1/models responds")


def step_c4_smoke(cfg, state, pr=None):
    """c4_smoke: collect one task, criterion = K files / last line final / seeds matching position by position."""
    pr = pr or Probes()
    mf = manifest_of(cfg)
    d, k, seeds = smoke_dir(cfg), k_of(cfg), seeds_of(cfg)
    # Check the seed table length first: if this comes after smoke_traj_check, a short seed table
    # would make seeds[i] raise IndexError first, and a human would see a traceback instead of
    # this blocked (review C10)
    if k > 1 and len(seeds) != k:
        return blocked("seed table does not match the trajectory count per task",
                       f"trajs_per_unit={k}, collect.seeds has {len(seeds)}"
                       f": {seeds}; align the two, then re-run")
    ok, why = smoke_traj_check(d, k, seeds, cfg["env"])
    if ok:
        return advanced("G4 smoke criteria already met", str(d))
    s0 = mf["servers"][0]
    preset = mf.get("gptoss_client_preset") or "default"
    cmd = PYRUN + ["collect-aw", "--preset", preset,
                   "--base-url", f"http://{s0['host']}:{s0['port']}/v1",
                   # The endpoint and model name are given explicitly from the manifest's servers[0], overriding
                   # the preset server section -- smoke hits the service this batch actually launched
                   "--model", cfg["model_full"],
                   "--split", "train", "--n", "1", "--max-steps", "30",
                   "--outdir", str(d), "--exp", f"{cfg['collect']['run_id']}smk"]
    if k > 1:
        cmd += ["--traj-per-task", str(k),
                "--seeds", ",".join(str(x) for x in seeds)]
    rc, _ = pr.run_cmd(cmd, cwd=ROOT, log=step_log(cfg, "c4_smoke"))
    if rc != 0:
        return blocked("smoke collection exited non-zero",
                       f"rc={rc}; log {step_log(cfg, 'c4_smoke')}")
    ok, why = smoke_traj_check(d, k, seeds, cfg["env"])
    if not ok:
        return blocked("G4 smoke criteria not met", why)
    return advanced("G4 smoke passed", f"{k} trajectories / seeds {seeds} match one to one")


def step_c5_clients(cfg, state, pr=None):
    """c5_clients: launch client pieces + the three registrations (G16's manual backfill path)."""
    pr = pr or Probes()
    bad = gate_manifest_unchanged(cfg, state, "launch collection client")
    if bad:
        return bad
    mf = manifest_of(cfg)
    bad = gate_clean_tree(pr, "launch collection client")
    if bad:
        return bad
    host = pr.local_host()
    sess = client_sessions(cfg)
    down = [s for s in sess if not pr.has_session(host, s)]
    fired = False
    if down:
        rc, _ = pr.run_cmd(["bash", "launch_clients.sh"], cwd=run_dir(cfg),
                           log=step_log(cfg, "c5_clients"))
        if rc != 0:
            return blocked("launch_clients.sh exited non-zero",
                           f"rc={rc}; log {step_log(cfg, 'c5_clients')}")
        fired = True
    ok, why = register_collect(cfg, pr, host, sess)
    if not ok:
        return blocked("the three registrations were not all completed", why)
    if fired:
        return launched(f"{len(down)} client pieces launched", f"the three registrations have been filled in; {len(sess)} pieces total")
    return advanced("all client pieces are up, registrations are complete", f"{len(sess)} pieces total")


def register_collect(cfg, pr, host, sess):
    """G16's three registrations: the job ledger (one client entry + one entry per service instance),
    record start, and RUNMETA. Already-registered ones are skipped -- a duplicate registration
    is rejected by the CLI on the spot (a guardrail, not an obstacle)."""
    rid = cfg["collect"]["run_id"]
    mf = manifest_of(cfg)
    names = pr.ledger_names()
    log = step_log(cfg, "c5_clients")
    if rid not in names:
        pieces = []
        for s in sess:
            pieces += ["--piece", f"{host}:cpu:{s}:{client_log(cfg, s)}"]
        rc, _ = pr.run_cmd(
            PYRUN + ["gpu-jobs", "register", "--name", rid,
                     "--workdir", str(run_dir(cfg)),
                     "--note", f"{cfg['run_family']} collection batch client {len(sess)} pieces"
                               f"({k_of(cfg)} per task, seeds {seeds_of(cfg)})"]
            + pieces, cwd=ROOT, log=log)
        if rc != 0:
            return False, f"gpu-jobs register {rid} exited {rc}"
    for i, s in enumerate(mf["servers"]):
        name = srv_job_name(cfg, i)
        if name in names:
            continue
        rc, _ = pr.run_cmd(
            PYRUN + ["gpu-jobs", "register", "--name", name,
                     "--workdir", str(SERVE_LOG_DIR),
                     "--note", f"{cfg['run_family']} collection batch {cfg['model_full']} "
                               f"instance (port {s['port']}), stays up for the whole collection, killed at wrap-up",
                     "--piece",
                     f"{s['host']}:{s['gpu']}:{s['session']}:"
                     f"{SERVE_LOG_DIR / (s['session'] + '.log')}",
                     "--kind", "service", "--port", str(s["port"])],
            cwd=ROOT, log=log)
        if rc != 0:
            return False, f"gpu-jobs register {name} exited {rc}"
    if "start" not in pr.record_events().get(rid, set()):
        rc, _ = pr.run_cmd(
            PYRUN + ["record", "start", "--run-id", rid,
                     "--track", f"collect_{rid}",
                     "--cmd", f"bash {run_dir(cfg) / 'launch_clients.sh'}",
                     "--host", host, "--gpu", "cpu",
                     "--model", cfg["model_full"],
                     "--data", str(outdir_of(cfg)),
                     "--log", str(run_dir(cfg) / "logs"),
                     "--note", f"{cfg['run_family']} collection: {k_of(cfg)} trajectories per task"],
            cwd=ROOT, log=log)
        if rc != 0:
            return False, f"record start {rid} exited {rc}"
    out = outdir_of(cfg)
    out.mkdir(parents=True, exist_ok=True)
    rc, _ = pr.run_cmd(PYRUN + ["runmeta", str(out), "--cmd",
                                f"bash {run_dir(cfg) / 'launch_clients.sh'}",
                                "--kind", "collect"], cwd=ROOT, log=log)
    if rc != 0:
        return False, f"runmeta {out} exited {rc}"
    return True, ""


def step_c6_done(cfg, state, pr=None):
    """c6_done: G6 completeness -> G7 GPU memory reaching zero -> deregister from the job ledger + record finish."""
    pr = pr or Probes()
    k, n = k_of(cfg), n_units(cfg)
    want = n * k
    files = traj_files(outdir_of(cfg), cfg["env"])
    bad_tail = [f.name for f in files if not is_final(f)]
    if len(files) != want or bad_tail:
        detail = (f"G6 not complete: {outdir_of(cfg)} has {len(files)} trajectory files,"
                  f"should have {n} tasks x {k} = {want}")
        if bad_tail:
            detail += f"; also {len(bad_tail)} whose last line is not final: {bad_tail[:5]}"
        host = pr.local_host()
        alive = [s for s in client_sessions(cfg) if pr.has_session(host, s)]
        if alive:
            return waiting("collection is still running", detail + f"; {len(alive)} client sessions still alive")
        return blocked("G6 not complete and all clients are dead",
                       detail + "; not a single client session is up -- "
                       "`bash launch_clients.sh` is idempotent and supports --resume, relaunch it to fill in the missing tasks")
    capped = [f.name for f in files if (final_steps(f) or 0) >= 30]
    mf = manifest_of(cfg)
    hot = []
    for s in mf["servers"]:
        if pr.has_session(s["host"], s["session"]):
            hot.append(f"{s['session']} is still alive (tmux kill-session -t {s['session']})")
            continue
        used = pr.gpu_used_mb(s["host"], s["gpu"])
        if used is None:
            hot.append(f"{s['host']}:{s['gpu']} GPU memory cannot be probed, treating as not yet zeroed")
        elif used > FREE_MB:
            hot.append(f"{s['host']}:{s['gpu']} still holds {used} MiB")
    if hot:
        return blocked("G7 GPU memory not zeroed",
                       "collection is complete, kill all service sessions first, then re-run:\n" + head_lines(hot))
    log = step_log(cfg, "c6_done")
    names = pr.ledger_names()
    for name in [cfg["collect"]["run_id"]] + [srv_job_name(cfg, i)
                                              for i in range(len(mf["servers"]))]:
        if name not in names:
            continue
        rc, _ = pr.run_cmd(PYRUN + ["gpu-jobs", "finish", name], cwd=ROOT, log=log)
        if rc != 0:
            return blocked("job ledger deregistration failed", f"gpu-jobs finish {name} exited {rc}")
    rid = cfg["collect"]["run_id"]
    evs = pr.record_events().get(rid, set())
    if "start" in evs and "finish" not in evs:
        # The numbers (task count / trajectory count / hits on the 30-step cap) are filled in by a human, the driver only closes out the state
        rc, _ = pr.run_cmd(
            PYRUN + ["record", "finish", rid, "--status", "ok",
                     "--metric", f"trajs={len(files)}", "--metric", f"units={n}",
                     "--metric", f"steps30_hit={len(capped)}"],
            cwd=ROOT, log=log)
        if rc != 0:
            return blocked("record wrap-up failed", f"record finish {rid} exited {rc}")
    return advanced("G6/G7 passed, job ledger and record have wrapped up",
                    f"{len(files)} trajectories ({n} tasks x {k}); 30-step cap hit by {len(capped)}")


# ---------------------------------------------------------------- annotate: three steps

def step_a1_stats(cfg, state, pr=None):
    """a1_stats: a pre-run of cut-point stats, then stop at the max_bounds ruling.
    If max_bounds is already written in the config, treat it as already ruled and do not stop again."""
    pr = pr or Probes()
    if "max_bounds" in cfg:
        return advanced("max_bounds already decided",
                        f"config has max_bounds={cfg['max_bounds']}, skipping the stop point")
    counts = pr.boundary_counts(cfg)
    if not counts:
        return blocked("no events found by the scan",
                       f"traj_runs={cfg['traj_runs']} model={cfg['model_full']} "
                       "no events found at all, first confirm the collection outputs and model name")
    st = dist_of(counts)
    state["cutpoint_stats"] = st
    print("cut count distribution (untruncated):" + json.dumps(st, ensure_ascii=False))
    return decide("cut distribution is out", json.dumps(st, ensure_ascii=False),
                  "max_bounds: keep 64 or raise it; after deciding, write max_bounds into the batch config, then re-run")


def step_a2_build(cfg, state, pr=None):
    """a2_build: the annotation chain build -> param_label -> check_callstr (same config).
    Completion criterion = all 13 outputs exist (the first 12 from build+param_label, the
    13th is the gate's output) and check_callstr returns 0."""
    pr = pr or Probes()
    miss = missing_artifacts(cfg)
    if not miss:
        return advanced(f"{len(annotate_artifacts(cfg))} annotation artifacts already exist",
                        str(data_out(cfg)))
    rc, _ = pr.run_cmd(PYRUN + ["recipe", "annotate-chain",
                                "--set", f"config={cfg['_path']}"],
                       cwd=ROOT, log=step_log(cfg, "a2_build"))
    if rc != 0:
        return blocked("annotation chain exited non-zero",
                       f"rc={rc} (gates A/B/D are hard-blocked in check_callstr);"
                       f"log {step_log(cfg, 'a2_build')}")
    miss = missing_artifacts(cfg)
    if miss:
        return blocked("annotation chain finished but the artifacts are incomplete", f"{data_out(cfg)} is missing {miss}")
    return advanced("annotation chain finished, artifacts complete", str(data_out(cfg)))


def step_a3_gates(cfg, state, pr=None):
    """a3_gates: G9 task-list line count + G11 spot-check files laid out + byte-for-byte rebuild comparison."""
    pr = pr or Probes()
    lists = split_lists(cfg)
    if not lists:
        return blocked("G9 has no task list to check", "config missing official_split_files")
    probs, counts = [], {}
    seen = {}
    for name, ids in lists.items():
        counts[name] = len(ids)
        if not ids:
            probs.append(f"{name} task list is empty")
        if len(set(ids)) != len(ids):
            probs.append(f"{name} task list has duplicate task_id")
        for u in ids:
            if u in seen and seen[u] != name:
                probs.append(f"task_id {u} is in both {seen[u]} and {name} piles")
            seen[u] = name
    if probs:
        return blocked("G9 task list check failed", "\n".join(probs[:10]))
    out = data_out(cfg)
    for n in ("qa_sample.txt", CHECK_FILE):
        if not (out / n).is_file():
            return blocked("G11 spot-check file does not exist", f"{out / n} does not exist")
    ref = out.parent / f"{out.name}_rebuild_ref"
    if ref.exists():
        return blocked("the backup from the last rebuild comparison is still there",
                       f"{ref} is the original-output backup left from the last byte-by-byte rebuild comparison -- "
                       "check it against the current output by hand before deleting it and redoing the rebuild")
    rebuild = list(BUILD_FILES) + list(PARAM_FILES)
    ref.mkdir(parents=True)
    for rel in rebuild:
        dst = ref / rel
        dst.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(out / rel, dst)
    log = step_log(cfg, "a3_gates")
    for task in ("ann-build", "ann-params"):
        rc, _ = pr.run_cmd(PYRUN + [task, "--config", cfg["_path"]],
                           cwd=ROOT, log=log)
        if rc != 0:
            return blocked("rebuild run failed",
                           f"{task} returned {rc}; the original-output backup is at {ref},"
                           "check by hand and decide whether to copy it back")
    diff = [rel for rel in rebuild
            if not filecmp.cmp(ref / rel, out / rel, shallow=False)]
    if diff:
        return blocked("byte-by-byte rebuild comparison mismatch",
                       f"{len(diff)} files differ between the two rebuilds: {diff};"
                       f"the first output's backup is at {ref} (do not delete it yet, it is evidence)")
    shutil.rmtree(ref)
    return advanced("G9/G11/byte-by-byte rebuild all passed",
                    f"task list {counts};{len(rebuild)} files identical byte-for-byte between the two rebuilds")


# ---------------------------------------------------------------- train: three steps

def step_t1_smoke(cfg, state, pr=None):
    """t1_smoke: run a three-cell smoke once for each training batch (= one base model x one
    training method).

    TODO (execution-block hardening): `launch-probe smoke` does not currently accept each
    cell's `--base/--lora/--grad-ckpt`, and the config's train section does not say which
    machine or which three cards smoke should use, so this step only checks the criterion and
    does not launch on the human's behalf -- if the criterion fails, it blocks and lists out
    exactly which batches still need to run; it does not let them through."""
    pr = pr or Probes()
    bad = gate_clean_tree(pr, "launch a training smoke test")
    if bad:
        return bad
    todo, notes = [], []
    for b in batches_of(cfg):
        for c in cells_of(cfg):
            rid = f"{b}_{cfg['model_short']}_{c}"
            d = RUNS_DIR / "smoke" / f"{rid}_smoke"
            ok, why, note = smoke_train_check(d, c)
            if not ok:
                todo.append(f"{rid}: {why}")
            elif note:
                notes.append(note)
    if not todo:
        detail = ("train_log has event=start and event=done, best/ exists;"
                  "ctool's ALIGN_CHECK PASS;"
                  "for cells with more than two event=step records, also checked that loss is decreasing")
        if notes:
            detail += "\n" + head_lines(notes, 12)
        return advanced(f"{len(batches_of(cfg))} batches x {len(cells_of(cfg))} cells "
                        "smoke criteria all passed", detail)
    return blocked("training smoke test has not passed yet",
                   head_lines(todo, 12) + "\nEach batch runs one 3-cell smoke, one cell per card:\n"
                   f"  python3 run.py launch-probe smoke --batch <batch> "
                   f"--data-root {data_root(cfg)} --env {cfg['env']} "
                   f"--model {cfg['model_short']} --host <host> --gpus a,b,c\n"
                   "(the 1.7B/4B and LoRA configs need --base/--lora/--grad-ckpt, which "
                   "the smoke config cannot take yet; launch those batches by hand for now, "
                   "the criteria to check are still the ones above)")


def step_t2_full(cfg, state, pr=None):
    """t2_full: launch full training batch by batch, following the card-scheduling table. One
    invocation launches only one batch, and returns 3 once it launches; only once all twelve
    runs finish (best/ exists + train_log has done) does it move to the next step.

    Each batch is launched only once: once it is launched, a marker is recorded in the state
    file, and on later invocations of this step, if the criterion is not met, it returns
    waiting (return 0) instead of calling launch-probe again. Without this, during the hours
    training runs, every invocation would relaunch the entire card-scheduling table -- for a
    slot that has already finished, its session is long gone and its card is free, so
    launch_probe would really relaunch it, run into the training script's B7 guard and exit
    immediately, but not before appending that completed run a false RUNMETA and stuffing
    run_id back into the job ledger's active list; and since launch_probe returns 0 whether or
    not it launched anything, the driver would keep reporting "launched" and returning 3
    forever (review C2/C7).
    """
    pr = pr or Probes()
    pend = []
    for rid in run_ids_of(cfg):
        ok, why = full_train_check(RUNS_DIR / rid)
        if not ok:
            pend.append((rid, why))
    if not pend:
        # If the criterion is met, advance regardless of whether the marker is present -- the marker is only used to block relaunches
        return advanced(f"{len(run_ids_of(cfg))} training runs all finished",
                        "best/ exists and train_log has event=done")
    pend_batches = [b for b in batches_of(cfg)
                    if any(rid.startswith(b + "_") for rid, _ in pend)]
    b = pend_batches[0]
    key = launch_key("t2_full", b)
    mark = launch_marker(state, key)
    if mark:
        return already_launched(
            f"{b} batch full-scale training", key, mark,
            f"unfinished runs: {[r for r, _ in pend]};"
            f"batches not yet reached: {[x for x in pend_batches if x != b] or 'none'}")
    bad = gate_clean_tree(pr, "launch full-scale training")
    if bad:
        return bad
    pl = placement_of(cfg, b)
    if not pl.exists():
        return blocked("card-scheduling table missing",
                       f"{pl} not found -- the card-scheduling table for batch {b} must be written to disk first"
                       "(one per batch, matching the shape of ops/p1b06_placement.json)")
    rc, _ = pr.run_cmd(PYRUN + ["launch-probe", "full", "--batch", b,
                                "--data-root", str(data_root(cfg)),
                                "--env", cfg["env"], "--placement", str(pl)],
                       cwd=ROOT, log=step_log(cfg, "t2_full"))
    if rc != 0:
        return blocked("launch-probe returned nonzero",
                       f"rc={rc}; log {step_log(cfg, 't2_full')}")
    mark_launched(state, key, f"launch-probe full --batch {b}")
    rest = [x for x in pend_batches if x != b]
    return launched(f"batch {b} launched",
                    f"batches not finished yet: {rest or 'none'};"
                    f"unfinished runs: {[r for r, _ in pend]}", advance=False)


def step_t3_close(cfg, state, pr=None):
    """t3_close: G16's three registrations complete + record finish for each run (numbers filled in by a human)."""
    pr = pr or Probes()
    names = pr.ledger_names()
    evs = pr.record_events()
    probs, todo = [], []
    for rid in run_ids_of(cfg):
        d = RUNS_DIR / rid
        if not (d / "RUNMETA.json").is_file():
            probs.append(f"{rid}: {d}/RUNMETA.json missing (G16, registration 3)")
        e = evs.get(rid, set())
        if "start" not in e:
            probs.append(f"{rid}: runs.jsonl has no start event (G16, registration 2)")
        elif "finish" not in e:
            todo.append(rid)
        if rid in names:
            probs.append(f"{rid}: still active in the job ledger, run gpu-jobs finish first")
    if probs:
        return blocked("G16 registration incomplete", head_lines(probs, 12))
    if todo:
        cmds = [f"  python3 run.py record finish {rid} --status ok "
                f"--metric <number> --conclusion <one sentence>" for rid in todo]
        return blocked("some runs still have no numbers recorded",
                       f"{len(todo)} runs have start but no finish; the numbers need to be filled in by hand:\n"
                       + head_lines(cmds, 12))
    return advanced(f"{len(run_ids_of(cfg))} runs have all three registrations complete and numbers recorded", "")


# ---------------------------------------------------------------- eval: three steps

def step_e1_tool(cfg, state, pr=None):
    """e1_tool: evaluate ctool first for each batch (launch-eval has its own dependency lock and
    registration built in). Completion criterion = each batch's REPLAY_REPORT.json exists.
    The launch marker works the same as t2_full (review C2/C7): once launched, do not relaunch;
    if the criterion is not met, just wait, and do not report a false launch."""
    pr = pr or Probes()
    pend = [b for b in batches_of(cfg)
            if not (RUNS_DIR / f"{b}_{cfg['model_short']}_ctool"
                    / "REPLAY_REPORT.json").is_file()]
    if not pend:
        return advanced(f"{len(batches_of(cfg))} batches have all ctool reports present", "")
    b = pend[0]
    key = launch_key("e1_tool", b)
    mark = launch_marker(state, key)
    if mark:
        return already_launched(f"batch {b} ctool eval", key, mark,
                                f"batches with no report yet: {pend or 'none'}")
    bad = gate_clean_tree(pr, "launch tool-cell eval")
    if bad:
        return bad
    pl = placement_of(cfg, b, "eval_tool")
    if not pl.exists():
        return blocked("eval card-scheduling table missing",
                       f"{pl} not found (matching the shape of ops/p1b06_eval_tool_placement.json)")
    rc, _ = pr.run_cmd(PYRUN + ["launch-eval", "tool", "--batch", b,
                                "--data-root", str(data_root(cfg)),
                                "--env", cfg["env"], "--placement", str(pl)],
                       cwd=ROOT, log=step_log(cfg, "e1_tool"))
    if rc != 0:
        return blocked("launch-eval tool returned nonzero",
                       f"rc={rc}; log {step_log(cfg, 'e1_tool')}")
    mark_launched(state, key, f"launch-eval tool --batch {b}")
    return launched(f"batch {b} ctool eval launched", f"batches with no report yet: {pend[1:] or 'none'}",
                    advance=False)


def step_e2_call(cfg, state, pr=None):
    """e2_call: evaluate cgen/cparam (launches only once the same batch's ctool report exists).
    A batch where both θ tiers are null records N/A into the state, not a failure -- yielding
    on both tiers is the established convention (gates.md Sec. 3.4). The launch marker works
    the same as t2_full (review C2/C7): each batch launches only once, and once launched, it
    only waits and does not relaunch."""
    pr = pr or Probes()
    reports = {"cgen": "CALLGEN_REPORT.json", "cparam": "PARAM_REPORT.json"}
    na, pend = [], []
    for b in batches_of(cfg):
        ctool = RUNS_DIR / f"{b}_{cfg['model_short']}_ctool"
        if theta_all_null(ctool):
            na.append(b)
            continue
        for c in ("cgen", "cparam"):
            if c not in cells_of(cfg):
                continue
            if not (RUNS_DIR / f"{b}_{cfg['model_short']}_{c}"
                    / reports[c]).is_file():
                pend.append(b)
                break
    state["theta_na_batches"] = na
    if not pend:
        return advanced("call-bracket reports all present",
                        f"batches where θ is null in both brackets, recorded N/A: {na or 'none'}")
    b = pend[0]
    key = launch_key("e2_call", b)
    mark = launch_marker(state, key)
    if mark:
        return already_launched(f"batch {b} call-bracket eval", key, mark,
                                f"batches with no report yet: {pend or 'none'};"
                                f"N/A: {na or 'none'}")
    bad = gate_clean_tree(pr, "launch call-cell eval")
    if bad:
        return bad
    pl = placement_of(cfg, b, "eval_call")
    if not pl.exists():
        return blocked("eval card-scheduling table missing",
                       f"{pl} not found (matching the shape of ops/p1b06_eval_call_placement.json)")
    rc, _ = pr.run_cmd(PYRUN + ["launch-eval", "call", "--batch", b,
                                "--data-root", str(data_root(cfg)),
                                "--env", cfg["env"], "--placement", str(pl)],
                       cwd=ROOT, log=step_log(cfg, "e2_call"))
    if rc != 0:
        return blocked("launch-eval call returned nonzero",
                       f"rc={rc}; log {step_log(cfg, 'e2_call')}")
    mark_launched(state, key, f"launch-eval call --batch {b}")
    return launched(f"batch {b} call-bracket eval launched",
                    f"batches with no report yet: {pend[1:] or 'none'}; N/A: {na or 'none'}",
                    advance=False)


def step_m1_matrix(cfg, state, pr=None):
    """m1_matrix: produce one matrix for each of the two risk tiers (one per batch). Done once the output exists."""
    pr = pr or Probes()
    log = step_log(cfg, "m1_matrix")
    made = []
    for b in batches_of(cfg):
        for risk in ("0.05", "0.1"):
            out = RUNS_DIR / f"MATRIX_{b}_r{risk}.md"
            if out.is_file():
                continue
            rc, _ = pr.run_cmd(PYRUN + ["matrix", "--runs-dir", str(RUNS_DIR),
                                        "--out", str(out), "--prefix", b,
                                        "--risk", risk,
                                        "--models", cfg["model_short"]],
                               cwd=ROOT, log=log)
            if rc != 0:
                return blocked("matrix returned nonzero", f"{b} risk {risk} rc={rc}; log {log}")
            if not out.is_file():
                return blocked("matrix finished running but the output is missing", str(out))
            made.append(out.name)
    return advanced("matrices for both risk brackets produced", f"newly produced this time: {made or 'none (already existed)'}")


# ---------------------------------------------------------------- step table

STEPS = (
    dict(name="c1_gen", stage="collect", fn=step_c1_gen,
         desc="generate the three launch artifacts for the collection batch"),
    dict(name="c2_servers", stage="collect", fn=step_c2_servers,
         desc="G1 dirty-tree check + G2 probe the cards + launch vLLM instances"),
    dict(name="c3_health", stage="collect", fn=step_c3_health,
         desc="G3 service health"),
    dict(name="c4_smoke", stage="collect", fn=step_c4_smoke,
         desc="G4 one-task collection smoke test"),
    dict(name="c5_clients", stage="collect", fn=step_c5_clients,
         desc="launch client pieces + G16 the three registrations"),
    dict(name="c6_done", stage="collect", fn=step_c6_done,
         desc="G6 completeness + G7 GPU memory back to zero + deregister"),
    dict(name="a1_stats", stage="annotate", fn=step_a1_stats,
         desc="cut-point distribution stats (max_bounds stop points)"),
    dict(name="a2_build", stage="annotate", fn=step_a2_build,
         desc="annotation chain: build/params/check"),
    dict(name="a3_gates", stage="annotate", fn=step_a3_gates,
         desc="G9 task list + G11 spot-check sample + byte-by-byte rebuild comparison"),
    dict(name="t1_smoke", stage="train", fn=step_t1_smoke,
         desc="3-cell smoke test per batch"),
    dict(name="t2_full", stage="train", fn=step_t2_full,
         desc="launch full-scale training per the card-scheduling table"),
    dict(name="t3_close", stage="train", fn=step_t3_close,
         desc="G16 registration check + record numbers run by run"),
    dict(name="e1_tool", stage="eval", fn=step_e1_tool,
         desc="ctool eval per batch"),
    dict(name="e2_call", stage="eval", fn=step_e2_call,
         desc="cgen/cparam eval"),
    dict(name="m1_matrix", stage="eval", fn=step_m1_matrix,
         desc="each of the two risk brackets gets its own matrix"),
)
STEP_NAMES = [s["name"] for s in STEPS]


def step_by_name(name):
    for s in STEPS:
        if s["name"] == name:
            return s
    raise SystemExit(f"unrecognized step name: {name}")


# ---------------------------------------------------------------- entry point

def print_status(cfg, st):
    print(f"pipeline {st['run_family']}  config {st.get('config')}")
    print(f"  current: {st.get('stage')} / {st['step']}  status {st['status']}")
    if st.get("reason"):
        print("  reason: " + str(st["reason"]).replace("\n", "\n        "))
    if st.get("decision_needed"):
        print(f"  awaiting ruling: {st['decision_needed']}")
    if st.get("cutpoint_stats"):
        print("  cut-point distribution: " + json.dumps(st["cutpoint_stats"], ensure_ascii=False))
    if st.get("launched"):
        # A human should be able to see which batch and which step have already been launched, and when
        print("  launch marker: " + ", ".join(
            f"{k}@{v.get('t')}" for k, v in sorted(st["launched"].items())))
    done = st["step"] == "done"
    idx = len(STEPS) if done else STEP_NAMES.index(st["step"])
    for i, s in enumerate(STEPS):
        mark = "x" if i < idx else (">" if i == idx else " ")
        print(f"  [{mark}] {s['name']:<12} {s['desc']}")
    for h in st.get("history", [])[-5:]:
        print(f"  {h['t']}  {h['step']:<12} {h['event']}")
    print(f"  state file: {state_path(cfg)}")
    return 0


def main(argv):
    cfg_path, only_status = None, False
    it = iter(argv)
    for a in it:
        if a == "--config":
            cfg_path = next(it, None)
            if cfg_path is None:
                raise SystemExit("--config must be followed by a batch config json")
        elif a == "--status":
            only_status = True
        elif a in ("-h", "--help"):
            print(__doc__)
            return 0
        else:
            raise SystemExit(f"unrecognized argument: {a} (only --config / --status are recognized)")
    if not cfg_path:
        raise SystemExit("--config <batch config json> is required (see run.py show pipeline for usage)")
    cfg = load_cfg(cfg_path)
    st = load_state(cfg)
    if only_status:
        return print_status(cfg, st)
    if st["step"] == "done":
        print(f"pipeline {cfg['run_family']} is fully complete. State: {state_path(cfg)}")
        return 0
    step = step_by_name(st["step"])
    print(f"[{step['name']}] {step['desc']}")
    event, code = step["fn"](cfg, st)
    apply_event(st, step, event)
    save_state(cfg, st)
    print(f"-> {event['status']}: {event['event']}")
    if event["detail"]:
        out = sys.stderr if code == 1 else sys.stdout
        print(event["detail"], file=out)
    if event["decision_needed"]:
        print(f"awaiting ruling: {event['decision_needed']}")
    nxt = "done" if st["step"] == "done" else st["step"]
    print(f"next step: {nxt}   state: {state_path(cfg)}   exit code {code}")
    return code


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
